export const br = {
  // TopBar
  'topbar.title': 'Bicofino',
  'topbar.subtitle': 'Brand System',
  'topbar.version': 'V1.1',
  'topbar.date': '// junho · 2026',

  // Overview
  'meta.eyebrow': '// DESIGN SYSTEM · V1.1',
  'overview.lead':
    'O sistema de design do Bicofino Group organiza os fundamentos visuais, verbais e operacionais que sustentam sua presença de marca. Feito para preservar coerência estética, clareza estratégica e reconhecimento em todas as vertentes — sem sacrificar velocidade operacional.',
  'overview.meta.version': 'VERSÃO',
  'overview.meta.published': 'PUBLICADO',
  'overview.meta.owner': 'OWNER',
  'overview.meta.base': 'BASE',
  'overview.meta.verticals': 'VERTICAIS',
  'foundations.eyebrow': '// 02.1 · Universo Visual',
  'foundations.title': 'Universo Visual',
  'foundations.lead':
    'O universo visual do Bicofino opera sobre quatro qualidades que são constante e pano de fundo — presentes em toda comunicação, de toda vertente, em qualquer formato.',

  // Colors
  'colors.title': 'Paleta de Cores',
  'colors.lead':
    'Cores estruturais que definem a identidade Bicofino. Paleta contida — poucos tons, bem aplicados. Destaques usados com máxima restrição.',
  'colors.basics.title': 'Cores Básicas',
  'colors.specials.title': 'Cores Especiais',
  'colors.highlights.label': '// 02.2.3 · máx 10% de superfície',
  'colors.highlights.title': 'Destaques',
  'colors.tokens.title': 'Color Tokens',
  'color.black.role': '// base · texto · wordmark',
  'color.steel.role': '// neutro · meta · captions',
  'color.aluminium.role': '// neutro · surface',
  'color.platinum.role': '// neutro · muted',
  'color.bg.role': '// surface · fundo padrão',
  'color.black.desc': 'Textos, bordas, elementos UI.',
  'color.steel.desc': 'Metadados, captions, ícones secundários.',
  'color.aluminium.desc': 'Superfícies secundárias, hover, chips.',
  'color.platinum.desc': 'Acentos sutis, muted-foreground.',
  'color.bg.desc': 'Fundo padrão do sistema.',
  'color.white.role': '// surface · cards · elevação',
  'color.white.desc': 'Cards, popovers, superfícies elevadas.',
  'color.powerblack.role': '// profundidade máxima · dark',
  'color.powerblack.desc': 'Fundo dark, máximo contraste.',
  'color.crema.role': '// fc bicofino',
  'color.caffe.role': '// fc bicofino',
  'color.champagne.role': '// champagne',
  'color.cacao.role': '// terroso · lab',
  'token.black.role': 'Textos, wordmark, bordas, elementos UI',
  'token.powerblack.role': 'Fundo dark, máximo contraste',
  'token.bg.role': 'Fundo padrão do sistema',
  'token.white.role': 'Cards, popovers, superfícies elevadas',
  'token.steel.role': 'Metadados, captions, ícones',
  'token.aluminium.role': 'Superfícies secundárias, hover, chips',
  'token.platinum.role': 'Muted foreground, acentos sutis',
  'token.crema.role': 'FC Bicofino — surface quente',
  'token.caffe.role': 'FC Bicofino — escuro quente',
  'token.cacao.role': 'Acento LAB — terroso, artesanal',
  'token.torino.role': 'Destaque editorial — acento principal',
  'token.como.role': 'Destaque alternativo — acento frio',
  'token.spfc.role': 'Destaque ADS — max 10% de superfície',
  'table.col.token': 'TOKEN',
  'table.col.value': 'VALUE',
  'table.col.name': 'NAME',
  'table.col.role': 'ROLE',

  // Typography
  'typography.title': 'Tipografia',
  'typography.lead':
    'Inter para texto editorial e UI. JetBrains Mono para metadados, eyebrows e código. Escala fechada — nenhum tamanho fora do sistema.',
  'font.inter.subtitle': 'Google Fonts · SIL Open Font License',
  'font.inter.family': 'Sans-serif editorial',
  'font.inter.weights': '400 · 500 · 600 · 700',
  'font.inter.coverage': '~95% do sistema',
  'font.inter.usage': 'Títulos, body, UI',
  'font.inter.license': 'SIL Open Font License',
  'font.mono.subtitle': 'Philipp Nurullin · JetBrains · Google Fonts',
  'font.mono.family': 'Monospaced',
  'font.mono.weights': '400 · 500',
  'font.mono.coverage': '~5% do sistema',
  'font.mono.usage': 'Metadados, eyebrows, código',
  'font.mono.license': 'SIL Open Font License',
  'font.gotham.subtitle': 'Hoefler & Co. · self-hospedada · só impacto',
  'font.gotham.family': 'Geométrica · impacto',
  'font.gotham.weights': '300 · 500 · 700 · 900 (+ itálicos)',
  'font.gotham.coverage': '<1% — 1 a 2 palavras',
  'font.gotham.usage': 'Nomes de atleta, títulos de post (uppercase)',
  'font.gotham.license': 'Comercial · licença Bicofino',
  'font.meta.family': 'Família',
  'font.meta.weights': 'Pesos',
  'font.meta.coverage': 'Cobertura',
  'font.meta.usage': 'Usos',
  'font.meta.license': 'Licença',
  'typescale.eyebrow.specimen': '// Secção / Categoria',
  'typescale.eyebrow.meta': '11 mono · 0.16em · 600 · uppercase',

  // Heading
  'slash.title': 'Heading',
  'slash.what.title': 'O que é',
  'slash.what.p1':
    'O Heading é o título de abertura de cada página ou seção principal do sistema Bicofino. Uma declaração tipográfica curta, direta e sem ornamento — palavras escolhidas que sustentam o peso de um hero sem precisar de frase completa.',
  'slash.what.p2':
    'O modelo de referência é “Connect. Curate. Create. Consult.” — quatro palavras, quatro pontos, impacto imediato. Sem verbo explícito. Sem explicação. O título não apresenta o conteúdo — ele é o conteúdo.',
  'slash.principles.title': 'Princípios',
  'slash.principle.short': 'Curto.',
  'slash.principle.short.desc': 'Cada palavra carrega peso. O título de hero nunca é uma frase — é uma posição.',
  'slash.principle.direct': 'Direto.',
  'slash.principle.direct.desc': 'Sem qualificadores, sem subordinadas, sem jargão. Se precisar de explicação, não é um heading.',
  'slash.principle.categorical': 'Categórico.',
  'slash.principle.categorical.desc': 'Afirma. Nunca interroga, nunca condiciona, nunca promete.',
  'slash.principle.singular': 'Singular.',
  'slash.principle.singular.desc': 'Um por página, um por seção. Nunca empilhado ou repetido na mesma composição.',
  'slash.typo.title': 'Especificação tipográfica',
  'slash.typo.col.element': 'Elemento',
  'slash.typo.col.type': 'Tipografia',
  'slash.typo.col.color': 'Cor',
  'slash.typo.row1': 'Heading principal',
  'slash.typo.row2': 'Heading sobre fundo escuro',
  'slash.typo.note':
    'Tamanho determinado pela escala fechada — display-xl (96px) para heroes de página, h1 (44px) para abertura de seção. Nunca fora da escala.',
  'slash.examples.title': 'Exemplos',
  'slash.examples.col.heading': 'Heading',
  'slash.examples.col.context': 'Contexto',
  'slash.ex1.context': 'Posicionamento — os 4 Cs',
  'slash.ex2.context': 'Tagline como heading de abertura',
  'slash.ex3.context': 'Apresentação das vertentes',
  'slash.ex4.context': 'Abertura do Design System',
  'slash.ex5.context': 'Hero de seção de conexões',
  'slash.ex6.context': 'Mídia kit — identificação do atleta',
  'slash.rejected.title': 'Exemplos recusados',
  'slash.rejected.col.proposal': 'Proposta',
  'slash.rejected.col.problem': 'Problema',
  'slash.rej1.proposal': '“Inovação para o futuro do esporte”',
  'slash.rej1.problem': 'Frase completa com jargão — não é heading',
  'slash.rej2.proposal': '“The Best Creative Studio In São Paulo”',
  'slash.rej2.problem': 'Superlativo vazio',
  'slash.rej3.proposal': '“Conectando marcas a atletas de alto nível”',
  'slash.rej3.problem': 'Gerúndio explicativo — texto de corpo, não título',
  'slash.rej4.proposal': '“Estratégia · Criatividade · Design · Execução · Resultados”',
  'slash.rej4.problem': 'Longo demais — perde o impacto',
  'slash.rej5.proposal': '“O que fazemos por você?”',
  'slash.rej5.problem': 'Interrogação — o Bicofino afirma, nunca pergunta',
  'slash.where.title': 'Onde aparece',
  'slash.where.item1': 'Hero de página e abertura de seção no site e no Brand System',
  'slash.where.item2': 'Capa e abertura de apresentações e dossiês',
  'slash.where.item3': 'Headline de mídia kits de atletas',
  'slash.where.item4': 'Momentos de abertura em campanhas e Bicofino Inspired',
  'slash.where.note':
    'No corpo de texto, em legendas, em propostas corridas e em copy de redes sociais, o Bicofino escreve em prosa direta. O heading existe apenas nos contextos acima — qualquer uso decorativo fora deles dilui o impacto.',

  // Spacing & Motion
  'spacing.title': 'Espaçamento & Motion',
  'spacing.lead':
    'Escala baseada em múltiplos de 4px. Motion quieto, curto e linear — sem overshoot, sem bounce.',
  'spacing.section.title': 'Espaçamento',
  'motion.section.title': 'Motion',
  'radius.section.title': 'Border Radius',
  'spacing.col.token': 'TOKEN',
  'spacing.col.px': 'PX',
  'spacing.col.rem': 'REM',
  'spacing.col.usage': 'USO TÍPICO',
  'spacing.col.visual': 'VISUAL',
  'sp1.uso': 'micro-gap inline',
  'sp2.uso': 'ícone ↔ label',
  'sp3.uso': 'padding pequeno',
  'sp4.uso': 'padding base',
  'sp5.uso': 'grid gutter',
  'sp6.uso': 'seção compacta',
  'sp7.uso': 'entre subsections',
  'sp8.uso': 'section padding',
  'sp9.uso': 'section padding · display',
  'radius.label.sm': 'sm',
  'radius.label.md': 'md',
  'radius.label.lg': 'lg',

  // Brand — Logo
  'brand.logo.title': 'Logotipo',
  'brand.logo.lead':
    'O logotipo Bicofino é a assinatura primária da marca. Sempre vetorial, sempre em uma das versões aprovadas abaixo.',
  'brand.logo.light': '// versão principal · sobre fundo claro',
  'brand.logo.dark': '// versão inversa · sobre fundo escuro',
  'brand.logo.crema': '// sobre crema · fc bicofino',
  'brand.logo.aluminium': '// sobre aluminium',
  'brand.logo.sizes.label': '// estudo de tamanho · logotipo',
  'brand.logo.sizes.display': 'display',
  'brand.logo.sizes.padrao': 'padrão',
  'brand.logo.sizes.compacto': 'compacto',
  'brand.logo.sizes.minimo': 'mínimo',
  'brand.logo.sizes.evitar': 'evitar',
  'brand.logo.minrec': '// mínimo recomendado: 48px de largura',
  'brand.logo.rules.label': '// regras',
  'brand.logo.rule1': 'Nunca distorcer, rotacionar ou alterar proporções.',
  'brand.logo.rule2': 'Manter espaço de proteção mínimo equivalente à altura do "B".',
  'brand.logo.rule3': 'Usar apenas as versões aprovadas — preto, branco, ou caffè sobre crema.',
  'brand.logo.rule4': 'Nunca aplicar efeitos, gradientes ou sombras.',
  'brand.diamond.label': '// Diamante',
  'brand.diamond.lead':
    'O símbolo isolado da marca. A estrela de quatro pontas ✦ — quatro eixos de precisão, equilíbrio, brilho contido. O Diamond carrega visualmente a mesma metáfora do nome: o bico fino que filtra, que permite a passagem apenas do que merece. Quatro pontas convergindo num centro exato — curadoria com forma.',
  'brand.diamond.lead2': 'Usado como marca standalone quando o logotipo completo não cabe ou não é necessário.',
  'brand.diamond.light': '// sobre fundo claro',
  'brand.diamond.dark': '// sobre fundo escuro',
  'brand.diamond.crema': '// sobre crema · fc bicofino',
  'brand.diamond.aluminium': '// sobre aluminium',
  'brand.diamond.sizes.label': '// estudo de tamanho · diamante',
  'brand.diamond.minrec': '// mínimo recomendado: 20px',

  // Voice & Tone
  'voice.title': 'Voice & Tone',
  'voice.lead':
    'A comunicação Bicofino é direta, precisa e confiante. Nunca genérica. Fala com autoridade sem arrogância — como alguém que conhece o que faz.',
  'voice.direct.label': 'Direto',
  'voice.direct.desc': 'Sem floreios. Uma frase, uma ideia. Nada de jargões desnecessários.',
  'voice.confident.label': 'Confiante',
  'voice.confident.desc': 'Afirma. Não "talvez", não "pode ser". Quando fala, sabe o que diz.',
  'voice.editorial.label': 'Editorial',
  'voice.editorial.desc': 'Tom curado. Palavras escolhidas. Ritmo próprio — Lead / Slash / Echo.',
  'voice.nocliches.label': 'Sem clichês',
  'voice.nocliches.desc': 'Nunca "inovador", "disruptivo", "de ponta". São palavras vazias.',
  'voice.bilingual.label': 'Bilíngue',
  'voice.bilingual.desc': 'Português brasileiro como língua principal. Inglês quando necessário.',

  // Verticais
  'verticais.title': 'Verticais',
  'verticais.lead':
    'O Bicofino Group opera em duas frentes editoriais. Cada uma tem expressão visual própria, dentro do sistema.',
  'verticais.onfield.desc':
    'Futebol. Competição. Resultados. Comunicação de alta intensidade — destaques visuais, cores de programa, urgência editorial.',
  'verticais.offfield.desc':
    'Lifestyle. Cultura. Alto padrão de vida. Comunicação editorial sofisticada — quiet luxury, espaço em branco, tipografia, restraint.',

  // Components — Buttons
  'buttons.title': 'Buttons',
  'buttons.lead':
    'Componentes compostos a partir dos tokens. Hierarquia por peso e contraste — não por tamanho de borda ou cor extra.',
  'buttons.primary.label': '// Primary · Ghost · Link',
  'buttons.inverse.label': '// Inverse · sobre fundo escuro',
  'btn.start': 'Começar projeto',
  'btn.playbook': 'Ver playbook',
  'btn.brand': 'brand.json →',
  'btn.manifesto': 'Ver manifesto',
  'btn.case': 'Abrir case',
  'btn.class.primary': '.btn-primary',
  'btn.class.ghost': '.btn-ghost',
  'btn.class.link': '.btn-link',
  'btn.class.primary.desc': '// fundo bf Black',
  'btn.class.ghost.desc': '// borda + fill on hover',
  'btn.class.link.desc': '// inline editorial',
  'btn.inverse.class': '.btn-ghost.inverse',
  'btn.inverse.desc': '// sobre fundo escuro',

  // Components — Badges
  'badges.title': 'Badges',
  'badges.lead':
    'Etiquetas de estado e categoria. Sempre monocromáticas dentro do sistema base — cor de programa apenas em contexto ADS.',

  // Components — Forms
  'forms.title': 'Forms',
  'forms.lead':
    'Hierarquia clara entre label, input e helper text. Mínimo de fricção. Error states usam cor com parcimônia — preferir mensagem inline.',
  'form.name': 'Nome',
  'form.email': 'Email',
  'form.message': 'Mensagem',
  'form.message.placeholder': 'Escreva aqui...',
  'form.website': 'Website',
  'form.website.error': 'URL inválida. Inclua https://',
  'form.access': 'Código de acesso',
  'form.access.helper': 'Campo desabilitado.',

  // Components — Cards
  'cards.title': 'Cards',
  'cards.lead': 'Editorial cards. Usados para destacar conteúdo com hierarquia clara.',
  'card.onfield.tag': 'Resultado',
  'card.onfield.title': 'Bicofino FC 3–1 Rival FC',
  'card.onfield.meta': 'Campeonato · Rodada 12',
  'card.offfield.tag': 'Editorial',
  'card.offfield.title': 'A arte da coleção cápsula',
  'card.offfield.meta': 'Lifestyle · Abril 2026',
  'card.ads.tag': 'Campanha',
  'card.ads.title': 'Brief de campanha — Q2',
  'card.ads.meta': 'ADS · Kick-off maio',

  // Governance
  'governance.title': 'Versão & Owners',
  'governance.lead':
    'Cada camada do sistema tem um responsável claro. Mudanças nos Foundations requerem revisão dos owners. Components e Patterns podem ser propostos por qualquer membro da equipe.',
  'governance.col.layer': 'LAYER',
  'governance.col.owner': 'OWNER',
  'governance.col.scope': 'SCOPE',
  'governance.foundations.scope': 'Tokens, tipografia, paleta, grid',
  'governance.brand.scope': 'Wordmark, voz, verticais',
  'governance.components.scope': 'UI patterns, código React/CSS',
  'governance.governance.scope': 'Versão, changelogs, arquivos',

  // Resources
  'resources.title': 'Resources',
  'resources.col.file': 'ARQUIVO',
  'resources.col.purpose': 'PROPÓSITO',
  'resource.tokens.css': 'CSS custom properties — fonte de verdade para tokens',
  'resource.tokens.ts': 'TypeScript constants — mesmos tokens, tipados',
  'resource.globals.css': 'CSS base completo — tokens + estilos base',
  'resource.design.md': 'Manual de Identidade Visual — fonte de verdade editorial',
  'resource.claude.md': 'Instruções para agentes de IA',
  'resource.storybook': 'Componentes interativos — laboratório técnico',
  'resource.docs.site': 'Este site — documentação editorial de alto padrão',
  'resource.design.system': 'Tokens compartilhados entre todos os apps',

  // Sidebar
  'nav.group.foundations': '// 02 · Design System',
  'nav.overview': 'Overview',
  'nav.bs.cover': 'Brand System',
  'nav.indice': 'Índice',
  'nav.fundamentos': 'Fundamentos',
  'nav.posicionamento': 'Posicionamento',
  'nav.nucleo': 'Núcleo da Marca',
  'nav.verbal': 'Universo Verbal',
  'nav.universo': 'Universo Visual',
  'nav.colors': 'Cores',
  'nav.typography': 'Tipografia',
  'nav.slash': 'Heading',
  'nav.spacing': 'Espaçamento & Motion',
  'nav.group.brand': '// 03 · Brand',
  'nav.logo': 'Logotipo',
  'nav.voice': 'Voz & Tom',
  'nav.verticais': 'Verticais',
  'nav.onfield.img': 'On Pitch — Image System',
  'nav.group.components': '// 04 · Componentes',
  'nav.buttons': 'Botões',
  'nav.badges': 'Badges',
  'nav.forms': 'Forms',
  'nav.cards': 'Cards',
  'nav.group.operacoes': '// 07 · Operações',
  'nav.operacoes': 'Arquitetura de Marca',
  'nav.delivery': 'Padrões de Entrega',
  'nav.group.governance': '// 08 · Governança',
  'nav.governance': 'Versão & Owners',
  'nav.resources': 'Resources',
  'nav.group.performance': '// 06 · Assets',
  'nav.performance': 'Motion Intelligence',
  'nav.sponsors': 'Sponsors',
  'nav.icons': 'Icons',
  'sidebar.tagline': '// unlike any other.',
  'sidebar.version': '// v1.1 · junho 2026',
  'sidebar.location': '// São Paulo · BR',

  // Footer
  'footer.system': '// Sistema',
  'footer.system.value': 'Foundations · Brand · Components · Governance',
  'footer.docs': '// Documentos',
  'footer.docs.value': 'DESIGN.md · tokens.css · tokens.ts · README',
  'footer.verticals': '// Verticais',
  'footer.verticals.value': 'On Pitch · Off Pitch',
  'footer.creative': '// Direção Criativa',
  'footer.tagline': '// unlike any other.',
  'footer.meta1': '// design system v1.1',
  'footer.meta2': '// junho · 2026',
  'footer.meta3': '// São Paulo · Brasil',
  // Footer espelhado do apps/web (valores idênticos aos de apps/web/content/br.ts)
  'footer.address': 'av pedroso de morais 1619 | 05019 001 | pinheiros | são paulo | sp | brasil',
  'footer.club': 'CLUB',
  'footer.club.label': 'Acesso ao Club',
  'footer.email': 'hello@bicofino.com',
  'footer.instagram': 'bicofino',
  'footer.instagram.label': 'Bicofino no Instagram',
  'footer.copyright': '© 2010 — now | BICOFINO GROUP S.A.',
  'footer.privacy': 'Privacidade',
  'footer.privacy.label': 'Política de Privacidade',
  'footer.cookies': 'Cookies',
  'footer.cookies.label': 'Política de Cookies',
  'page.footer.line':'// Bicofino Design System v1.1 — São Paulo, SP, Brasil — Junho 2026',

  // Performance Intelligence
  'perf.eyebrow': '// 06.1 · Motion Intelligence',
  'perf.title': 'Performance Intelligence',
  'perf.lead': 'Visualização viva do sistema Bicofino OS. Cada número representa eficiência real — tempo recuperado, output amplificado, custo eliminado. As métricas pulsam para lembrar que os dados são ativos, não estáticos.',
  'perf.metrics.label': '// 06.1.1 · Alive Components',
  'perf.metrics.title': 'Métricas do Sistema',
  'perf.chart.label': '// 06.1.2 · Sistema vs Tradicional',
  'perf.chart.title': 'Bicofino OS vs. Tradicional',
  'perf.chart.lead': 'A vantagem composta do Bicofino OS. A linha tradicional cresce linearmente — o sistema Bicofino cresce exponencialmente. A área entre elas representa eficiência gerada.',
  'perf.card1.label': 'Tempo Salvo / Semana',
  'perf.card1.desc': 'Por consultor',
  'perf.card2.label': 'Multiplicador de Output',
  'perf.card2.desc': 'vs. fluxo tradicional',
  'perf.card3.label': 'Redução de Custo',
  'perf.card3.desc': 'Overhead operacional',
  'perf.card4.label': 'Ganho de Eficiência',
  'perf.card4.desc': 'Ano a ano',
  'perf.card5.label': 'Agentes Ativos',
  'perf.card5.desc': 'Em paralelo',
  'perf.card6.label': 'Tempo de Resposta',
  'perf.card6.desc': 'Latência média do sistema',

  // Sponsors
  'sponsors.eyebrow': '// 06.2 · Sponsors',
  'sponsors.title': 'Sponsors',
  'sponsors.lead': 'Marcas globais e empresas de referência com as quais o Bicofino mantém relações próximas — construídas com acesso, confiança e contexto estratégico ao longo do tempo.',

  // Icons
  'icons.eyebrow': '// 06.3 · Icons',
  'icons.title': 'Icons',
  'icons.lead': 'Sistema de ícones baseado em Lucide. Traço consistente, peso único, escala previsível. Clique em qualquer ícone para copiar o snippet React.',

  // On Pitch
  'onfield.eyebrow': '// 05.2 · On Pitch — Image System',
  'onfield.title': 'On Pitch — Athlete Image System',
  'onfield.intro.eyebrow': 'Imagem como presença. Dados como prova.',
  'onfield.intro.lead': 'O sistema On Pitch trata o atleta como o principal ativo visual. As imagens não são colocadas dentro de cards genéricos — elas criam hierarquia, tensão e presença. Os dados sustentam a narrativa com precisão.',
  'onfield.catalog.eyebrow': '// 05.2.2 · Asset Catalog',
  'onfield.catalog.title': 'Estrutura de Assets On Pitch',
  'onfield.catalog.col.category': 'Categoria',
  'onfield.catalog.col.path': 'Pasta',
  'onfield.catalog.col.format': 'Formato',
  'onfield.catalog.col.note': 'Observação',
  'onfield.cat.portraits': 'Retratos de Atletas',
  'onfield.cat.campaigns': 'Imagens de Campanha',
  'onfield.cat.brand': 'Marca Pessoal',
  'onfield.cat.badges': 'Badges Bicofino',
  'onfield.cat.clubs': 'Escudos de Clubes',
  'onfield.cat.sponsors': 'Logos de Patrocinadores',
  'onfield.cat.passports': 'Passaportes / Nações',
  'onfield.cat.venues': 'Estádios',
  'onfield.cat.tournaments': 'Torneios',
  'onfield.cat.icons': 'Ícones de Performance',
  'onfield.cat.portraits.note': 'Corpo inteiro ou busto, fundo branco removido',
  'onfield.cat.campaigns.note': 'Sessões editoriais, vertical preferido',
  'onfield.cat.brand.note': 'Wordmarks, monogramas, logos pessoais',
  'onfield.cat.badges.note': 'Pro, FC, Day e badges de eventos',
  'onfield.cat.clubs.note': 'Escudos oficiais, variante mono preferida',
  'onfield.cat.sponsors.note': 'Nike, Adidas, Puma — versões preto/branco',
  'onfield.cat.passports.note': 'Bandeiras de nacionalidade como tokens circulares',
  'onfield.cat.venues.note': 'Silhuetas de estádios e localizações',
  'onfield.cat.tournaments.note': 'Logos de copas, marcas de competições',
  'onfield.cat.icons.note': 'Velocidade, corpo, campo, troféu, tênis, etc.',

  // Operations
  'ops.eyebrow': '// 07 • OPERAÇÕES',
  'ops.title': 'Operações',
  'ops.lead': 'O Bicofino Group organiza suas operações em duas grandes vertentes e um projeto confidencial.',
  'ops.arch.label': '// 07.1',
  'ops.arch.title': 'Arquitetura de Marca',
  'ops.onfield.title': 'ON PITCH',
  'ops.onfield.subtitle': '*Tudo relativo ao atleta e sua performance em campo*',
  'ops.onfield.desc': 'On Pitch reúne todos os serviços e especialistas dedicados ao atleta como performer. Médicos, especialistas em performance física, nutricionistas, psicólogos esportivos, coaches táticos, tecnologia de análise de dados — tudo que potencializa o atleta dentro do campo e garante que ele chegue ao mais alto nível de competição.',
  'ops.onfield.delivers.label': 'O que On Pitch entrega:',
  'ops.onfield.d1': 'Agenciamento e representação de atletas',
  'ops.onfield.d2': 'Desenvolvimento físico, tático, mental e cognitivo',
  'ops.onfield.d3': 'Monitoramento de performance e saúde',
  'ops.onfield.d4': 'Gestão de contratos com clubes',
  'ops.onfield.d5': 'Posicionamento para mercados internacionais (pipeline Europa)',
  'ops.onfield.d6': 'Media kit e perfil de atleta para scouts e clubes',
  'ops.onfield.serves.label': 'Quem serve:',
  'ops.onfield.serves.desc': 'Atletas do portfólio Bicofino — principalmente jovens talentos do futebol com potencial de carreira internacional.',
  'ops.offfield.title': 'OFF PITCH',
  'ops.offfield.subtitle': '*Tudo que existe fora do campo*',
  'ops.offfield.desc': 'Off Pitch reúne todos os serviços que fazem o atleta, a marca ou a empresa crescer além da performance esportiva. É aqui que o Bicofino também serve marcas e empresas — com ou sem conexão direta com atletas.',
  'ops.offfield.delivers.label': 'O que Off Pitch entrega:',
  'ops.offfield.d1': 'Branding e identidade visual (atletas, marcas, empresas)',
  'ops.offfield.d2': 'Advertising e produção de conteúdo',
  'ops.offfield.d3': 'Design, motion e direção de arte',
  'ops.offfield.d4': 'PR e personal branding executivo',
  'ops.offfield.d5': 'Consultoria jurídica e planejamento tributário',
  'ops.offfield.d6': 'Family office e planejamento financeiro (Wealth)',
  'ops.offfield.d7': 'Conexão entre marcas, empresas, atletas e personalidades',
  'ops.offfield.serves.label': 'Quem serve:',
  'ops.offfield.serves.desc': 'Atletas do portfólio (no extra-campo), marcas que querem conexão com o universo do esporte e do luxo, executivos e empresas que buscam curadoria criativa e estratégica de alto nível.',
  'ops.offfield.diff.label': 'O diferencial Off Pitch:',
  'ops.offfield.diff.desc': 'O Bicofino conecta marcas e empresas a atletas, celebridades e personalidades que estão fora do alcance da grande maioria. Esse acesso foi construído com anos de relacionamentos éticos, negociações limpas e presença consistente nos mercados certos. Toda conexão é estruturada para que todos os lados ganhem.',
  'ops.club.title': 'CLUB',
  'ops.club.subtitle': '*Território da Raposa — confidencial*',
  'ops.club.desc': 'O Club é o projeto mais íntimo e seletivo do Bicofino. Seu perfil, critérios e membros são mantidos em total discrição.',
  'ops.club.confidential': '*Detalhes não documentados publicamente neste Brand System.*',
  'ops.visual.label': '// Arquitetura visual das vertentes',
  'ops.visual.desc': 'On Pitch e Off Pitch compartilham o mesmo DNA visual — Inter, diamond ✦, paleta core, hierarquia de leitura. O que diferencia uma da outra é o universo de imagem:',
  'ops.visual.onfield': 'sempre imagens dos atletas em campo, em treino, em competição',
  'ops.visual.offfield': 'imagens dos atletas em relação a marcas, campanhas, empresas e design — além de projetos que não envolvem atletas',
  'ops.delivery.label': '// 07.2',
  'ops.delivery.title': 'Padrões de Entrega',
  'ops.delivery.desc': 'Todo output do Bicofino passa pelo filtro dos 6 Princípios de Operação antes de ser entregue:',
  'ops.p1.title': 'Obsessão genuína por detalhes',
  'ops.p1.desc': 'Existe algo aqui que pode ser mais preciso?',
  'ops.p2.title': 'Beleza e inteligência no design',
  'ops.p2.desc': 'Esta entrega é ao mesmo tempo bonita e estratégica?',
  'ops.p3.title': 'Entregar mais que o esperado',
  'ops.p3.desc': 'O cliente vai perceber que recebeu além do briefing?',
  'ops.p4.title': 'Simples, nunca simplista',
  'ops.p4.desc': 'Existe algo que pode ser cortado sem perder substância?',
  'ops.p5.title': 'Contundência com elegância',
  'ops.p5.desc': 'A mensagem é clara e está entregue com o tom correto?',
  'ops.p6.title': 'Tecnologia a serviço da criatividade',
  'ops.p6.desc': 'IA e dados foram usados como amplificadores?',
  'ops.tools.label': '// Ferramentas de operação',
  'ops.tools.col.role': 'FUNÇÃO',
  'ops.tools.col.tool': 'FERRAMENTA',
  'ops.tool.memory.role': 'Memória',
  'ops.tool.memory.name': 'Google Drive + Supabase (banco de dados e memória local para agentes)',
  'ops.tool.org.role': 'Organização',
  'ops.tool.org.name': 'Dashboard próprio em desenvolvimento (sem Notion)',
  'ops.tool.orch.role': 'Orquestração',
  'ops.tool.orch.name': 'Claude no terminal via Google Antigravity · Agentes de IA em desenvolvimento e implementação',
  'ops.tool.intel.role': 'Inteligência / Estratégia / Copy',
  'ops.tool.intel.name': 'Claude (primário) · ChatGPT · Gemini',
  'ops.tool.design.role': 'Design / Interface',
  'ops.tool.design.name': 'Photoshop · Illustrator · Claude Code (React, Tailwind, shadcn, Storybook)',
  'ops.tool.vi.role': 'Identidade Visual',
  'ops.tool.vi.name': 'Pacote Adobe',
  'ops.tool.video.role': 'Edição de Vídeo',
  'ops.tool.video.name': 'Adobe Premiere',
  'ops.tool.motion.role': 'Motion',
  'ops.tool.motion.name': 'Claude Code (componentes) · After Effects · Magnific',
  'ops.tool.imggen.role': 'Geração de Imagens',
  'ops.tool.imggen.name': 'Magnific · Nano Banana · ChatGPT',
  'ops.tool.vidgen.role': 'Geração de Vídeo',
  'ops.tool.vidgen.name': 'Magnific · Google VEO',
  'ops.flow.label': '// Fluxo de entrega Off Pitch — Studio',
  'ops.flow.step1': 'Briefing ou entrada de demanda (sexta-feira preferencial)',
  'ops.flow.step2': 'Produção — 2 dias úteis para projetos recorrentes',
  'ops.flow.step3': 'Revisão interna — 1 dia útil',
  'ops.flow.step4': 'Entrega ao cliente',
  'ops.flow.step5': 'Rodada de ajuste inclusa no escopo',
  'ops.flow.step6': 'Aprovação e arquivamento',
  'ops.commercial.label': '// Política comercial',
  'ops.policy1': 'Sem desconto sobre valor. Ajuste via redução de escopo, nunca de qualidade.',
  'ops.policy2': 'Agenda limitada. Lista de espera quando necessário.',
  'ops.policy3': 'Honorários do Studio, budget de mídia e custos de produção são itens separados e independentes.',
  'ops.policy4': 'Toda proposta no formato dossiê — nunca lista de preços ou pacotes.',
  'ops.brand.line1': 'Brand System — Bicofino Group SA',
  'ops.brand.line2': 'Elaborado e mantido pelo Studio Bicofino',
  'ops.brand.line3': 'Woney Malian / Fabio Brancatelli',
  'ops.brand.version': 'v1.1 · São Paulo, BR · Junho 2026',
  'ops.brand.tagline': 'Unlike Any Other.',
} as const
