export const en = {
  // TopBar
  'topbar.title': 'Bicofino',
  'topbar.subtitle': 'Design System',
  'topbar.version': 'v2.0',
  'topbar.date': '// april · 2026',

  // Overview
  'meta.eyebrow': '// Brand System · v2.0',
  'overview.lead':
    'The Bicofino Group design system codifies the Visual Identity Manual into tokens, components, and reusable patterns. Built to maintain fidelity across verticals — On Field and Off Field — without sacrificing operational velocity.',
  'overview.meta.version': 'VERSION',
  'overview.meta.published': 'PUBLISHED',
  'overview.meta.owner': 'OWNER',
  'overview.meta.base': 'BASE',
  'overview.meta.verticals': 'VERTICALS',
  'foundations.eyebrow': '// 01 · Foundations',
  'foundations.title': 'Foundations',
  'foundations.lead':
    'Low-level decisions that everything else inherits — palette, typography, spacing, and motion. The only layer where new tokens may be introduced.',

  // Colors
  'colors.title': 'Color Palette',
  'colors.lead':
    'Structural colors that define Bicofino identity. Contained palette — few tones, well applied. Highlights used with maximum restraint.',
  'colors.basics.title': 'Core Colors',
  'colors.specials.title': 'Special Colors',
  'colors.highlights.label': '// 01.1.3 · max 10% of surface',
  'colors.highlights.title': 'Highlights',
  'colors.tokens.title': 'Color Tokens',
  'color.black.role': '// base · text · wordmark',
  'color.steel.role': '// neutral · meta · captions',
  'color.aluminium.role': '// neutral · surface',
  'color.platinum.role': '// neutral · muted',
  'color.bg.role': '// surface · default background',
  'color.black.desc': 'Text, borders, UI elements.',
  'color.steel.desc': 'Metadata, captions, secondary icons.',
  'color.aluminium.desc': 'Secondary surfaces, hover, chips.',
  'color.platinum.desc': 'Subtle accents, muted-foreground.',
  'color.bg.desc': 'Default system background.',
  'color.white.role': '// surface · cards · elevation',
  'color.white.desc': 'Cards, popovers, elevated surfaces.',
  'color.powerblack.role': '// maximum depth · dark',
  'color.powerblack.desc': 'Dark background, maximum contrast.',
  'color.crema.role': '// fc bicofino',
  'color.caffe.role': '// fc bicofino',
  'color.champagne.role': '// champagne',
  'color.cacao.role': '// earthy · lab',
  'token.black.role': 'Text, wordmark, borders, UI elements',
  'token.powerblack.role': 'Dark background, maximum contrast',
  'token.bg.role': 'Default system background',
  'token.white.role': 'Cards, popovers, elevated surfaces',
  'token.steel.role': 'Metadata, captions, icons',
  'token.aluminium.role': 'Secondary surfaces, hover, chips',
  'token.platinum.role': 'Muted foreground, subtle accents',
  'token.crema.role': 'FC Bicofino — warm surface',
  'token.caffe.role': 'FC Bicofino — warm dark',
  'token.cacao.role': 'LAB accent — earthy, artisanal',
  'token.torino.role': 'Editorial highlight — primary accent',
  'token.como.role': 'Alternative highlight — cool accent',
  'token.spfc.role': 'ADS highlight — max 10% of surface',
  'table.col.token': 'TOKEN',
  'table.col.value': 'VALUE',
  'table.col.name': 'NAME',
  'table.col.role': 'ROLE',

  // Typography
  'typography.title': 'Typography',
  'typography.lead':
    'Inter for editorial and UI text. JetBrains Mono for metadata, eyebrows, and code. Closed scale — no size outside the system.',
  'font.inter.subtitle': 'Google Fonts · SIL Open Font License',
  'font.inter.family': 'Editorial sans-serif',
  'font.inter.weights': '400 · 500 · 600 · 700',
  'font.inter.coverage': '~95% of the system',
  'font.inter.usage': 'Headlines, body, UI',
  'font.inter.license': 'SIL Open Font License',
  'font.mono.subtitle': 'Philipp Nurullin · JetBrains · Google Fonts',
  'font.mono.family': 'Monospaced',
  'font.mono.weights': '400 · 500',
  'font.mono.coverage': '~5% of the system',
  'font.mono.usage': 'Metadata, eyebrows, code',
  'font.mono.license': 'SIL Open Font License',
  'font.meta.family': 'Family',
  'font.meta.weights': 'Weights',
  'font.meta.coverage': 'Coverage',
  'font.meta.usage': 'Usage',
  'font.meta.license': 'License',
  'typescale.eyebrow.specimen': '// Section / Category',
  'typescale.eyebrow.meta': '11 mono · 0.16em · 600 · uppercase',

  // Slash Heading
  'slash.title': 'Slash Heading',
  'slash.lead':
    "Page opening title. Editorial structure in three parts — Lead · Slash · Echo — with Bicofino's own rhythm. Used as the single h1 in every page hero.",
  'slash.anatomy.label': '// anatomy',
  'slash.col.part': 'PART',
  'slash.col.role': 'ROLE',
  'slash.col.type': 'TYPOGRAPHY',
  'slash.col.color': 'COLOR (TOKEN)',
  'slash.lead.role': 'Primary statement',
  'slash.slash.role': 'Editorial divider',
  'slash.echo.role': 'Echo / counterpart',

  // Spacing & Motion
  'spacing.title': 'Spacing & Motion',
  'spacing.lead':
    'Scale based on multiples of 4px. Quiet, short, linear motion — no overshoot, no bounce.',
  'spacing.section.title': 'Spacing',
  'motion.section.title': 'Motion',
  'radius.section.title': 'Border Radius',
  'spacing.col.token': 'TOKEN',
  'spacing.col.px': 'PX',
  'spacing.col.rem': 'REM',
  'spacing.col.usage': 'TYPICAL USE',
  'spacing.col.visual': 'VISUAL',
  'sp1.uso': 'inline micro-gap',
  'sp2.uso': 'icon ↔ label',
  'sp3.uso': 'small padding',
  'sp4.uso': 'base padding',
  'sp5.uso': 'grid gutter',
  'sp6.uso': 'compact section',
  'sp7.uso': 'between subsections',
  'sp8.uso': 'section padding',
  'sp9.uso': 'section padding · display',
  'radius.label.sm': 'sm',
  'radius.label.md': 'md',
  'radius.label.lg': 'lg',

  // Brand — Logo
  'brand.logo.title': 'Logotype',
  'brand.logo.lead':
    'The Bicofino logotype is the primary brand signature. Always vector, always in one of the approved versions below.',
  'brand.logo.light': '// main version · on light background',
  'brand.logo.dark': '// inverse version · on dark background',
  'brand.logo.crema': '// on crema · fc bicofino',
  'brand.logo.aluminium': '// on aluminium',
  'brand.logo.sizes.label': '// size study · logotype',
  'brand.logo.sizes.display': 'display',
  'brand.logo.sizes.padrao': 'standard',
  'brand.logo.sizes.compacto': 'compact',
  'brand.logo.sizes.minimo': 'minimum',
  'brand.logo.sizes.evitar': 'avoid',
  'brand.logo.minrec': '// minimum recommended: 48px width',
  'brand.logo.rules.label': '// rules',
  'brand.logo.rule1': 'Never distort, rotate, or alter proportions.',
  'brand.logo.rule2': 'Maintain minimum clear space equal to the height of the "B".',
  'brand.logo.rule3': 'Use only approved versions — black, white, or caffè on crema.',
  'brand.logo.rule4': 'Never apply effects, gradients, or shadows.',
  'brand.diamond.label': '// Diamond',
  'brand.diamond.lead':
    'The diamond symbol is the isolated brand mark — used as a standalone graphic element when the full logotype does not fit or is not needed.',
  'brand.diamond.light': '// on light background',
  'brand.diamond.dark': '// on dark background',
  'brand.diamond.crema': '// on crema · fc bicofino',
  'brand.diamond.aluminium': '// on aluminium',
  'brand.diamond.sizes.label': '// size study · diamond',
  'brand.diamond.minrec': '// minimum recommended: 20px',

  // Voice & Tone
  'voice.title': 'Voice & Tone',
  'voice.lead':
    'Bicofino communication is direct, precise, and confident. Never generic. Speaks with authority without arrogance — like someone who knows their work.',
  'voice.direct.label': 'Direct',
  'voice.direct.desc': 'No flourishes. One sentence, one idea. No unnecessary jargon.',
  'voice.confident.label': 'Confident',
  'voice.confident.desc': "States. Not 'maybe', not 'perhaps'. When it speaks, it knows what it says.",
  'voice.editorial.label': 'Editorial',
  'voice.editorial.desc': 'Curated tone. Chosen words. Its own rhythm — Lead / Slash / Echo.',
  'voice.nocliches.label': 'No clichés',
  'voice.nocliches.desc': "Never 'innovative', 'disruptive', 'cutting-edge'. Empty words.",
  'voice.bilingual.label': 'Bilingual',
  'voice.bilingual.desc': 'Brazilian Portuguese as the primary language. English when needed.',

  // Verticais
  'verticais.title': 'Verticals',
  'verticais.lead':
    'Bicofino Group operates on two editorial fronts. Each has its own visual expression, within the system.',
  'verticais.onfield.desc':
    'Football. Competition. Results. High-intensity communication — visual highlights, program colors, editorial urgency.',
  'verticais.offfield.desc':
    'Lifestyle. Culture. Premium living. Sophisticated editorial communication — quiet luxury, white space, typography, restraint.',

  // Components — Buttons
  'buttons.title': 'Buttons',
  'buttons.lead':
    'Components built from tokens. Hierarchy through weight and contrast — not border size or extra color.',
  'buttons.primary.label': '// Primary · Ghost · Link',
  'buttons.inverse.label': '// Inverse · on dark background',
  'btn.start': 'Start project',
  'btn.playbook': 'View playbook',
  'btn.brand': 'brand.json →',
  'btn.manifesto': 'View manifesto',
  'btn.case': 'Open case',
  'btn.class.primary': '.btn-primary',
  'btn.class.ghost': '.btn-ghost',
  'btn.class.link': '.btn-link',
  'btn.class.primary.desc': '// bf Black background',
  'btn.class.ghost.desc': '// border + fill on hover',
  'btn.class.link.desc': '// inline editorial',
  'btn.inverse.class': '.btn-ghost.inverse',
  'btn.inverse.desc': '// on dark background',

  // Components — Badges
  'badges.title': 'Badges',
  'badges.lead':
    'Status and category labels. Always monochromatic within the base system — program color only in ADS context.',

  // Components — Forms
  'forms.title': 'Forms',
  'forms.lead':
    'Clear hierarchy between label, input, and helper text. Minimum friction. Error states use color sparingly — prefer inline messaging.',
  'form.name': 'Name',
  'form.email': 'Email',
  'form.message': 'Message',
  'form.message.placeholder': 'Write here...',
  'form.website': 'Website',
  'form.website.error': 'Invalid URL. Include https://',
  'form.access': 'Access code',
  'form.access.helper': 'Field disabled.',

  // Components — Cards
  'cards.title': 'Cards',
  'cards.lead': 'Editorial cards. Used to highlight content with clear hierarchy.',
  'card.onfield.tag': 'Result',
  'card.onfield.title': 'Bicofino FC 3–1 Rival FC',
  'card.onfield.meta': 'Championship · Round 12',
  'card.offfield.tag': 'Editorial',
  'card.offfield.title': 'The capsule collection art',
  'card.offfield.meta': 'Lifestyle · April 2026',
  'card.ads.tag': 'Campaign',
  'card.ads.title': 'Campaign brief — Q2',
  'card.ads.meta': 'ADS · May kick-off',

  // Governance
  'governance.title': 'Version & Owners',
  'governance.lead':
    'Each system layer has a clear owner. Changes to Foundations require owner review. Components and Patterns may be proposed by any team member.',
  'governance.col.layer': 'LAYER',
  'governance.col.owner': 'OWNER',
  'governance.col.scope': 'SCOPE',
  'governance.foundations.scope': 'Tokens, typography, palette, grid',
  'governance.brand.scope': 'Wordmark, voice, verticals',
  'governance.components.scope': 'UI patterns, React/CSS code',
  'governance.governance.scope': 'Version, changelogs, files',

  // Resources
  'resources.title': 'Resources',
  'resources.col.file': 'FILE',
  'resources.col.purpose': 'PURPOSE',
  'resource.tokens.css': 'CSS custom properties — source of truth for tokens',
  'resource.tokens.ts': 'TypeScript constants — same tokens, typed',
  'resource.globals.css': 'Full CSS base — tokens + base styles',
  'resource.design.md': 'Visual Identity Manual — editorial source of truth',
  'resource.claude.md': 'Instructions for AI agents',
  'resource.storybook': 'Interactive components — technical laboratory',
  'resource.docs.site': 'This site — premium editorial documentation',
  'resource.design.system': 'Shared tokens across all apps',

  // Sidebar
  'nav.group.foundations': '// 01 · Foundations',
  'nav.overview': 'Overview',
  'nav.colors': 'Colors',
  'nav.typography': 'Typography',
  'nav.slash': 'Slash Heading',
  'nav.spacing': 'Spacing & Motion',
  'nav.group.brand': '// 02 · Brand',
  'nav.logo': 'Logotype',
  'nav.voice': 'Voice & Tone',
  'nav.verticais': 'Verticals',
  'nav.group.components': '// 03 · Components',
  'nav.buttons': 'Buttons',
  'nav.badges': 'Badges',
  'nav.forms': 'Forms',
  'nav.cards': 'Cards',
  'nav.group.operacoes': '// 06 · Operations',
  'nav.operacoes': 'Brand Architecture',
  'nav.group.governance': '// 07 · Governance',
  'nav.governance': 'Version & Owners',
  'nav.resources': 'Resources',
  'sidebar.tagline': '// unlike any other.',
  'sidebar.version': '// v2.0 · april 2026',
  'sidebar.location': '// São Paulo · BR',

  // Footer
  'footer.system': '// System',
  'footer.system.value': 'Foundations · Brand · Components · Governance',
  'footer.docs': '// Documents',
  'footer.docs.value': 'DESIGN.md · tokens.css · tokens.ts · README',
  'footer.verticals': '// Verticals',
  'footer.verticals.value': 'On Field · Off Field',
  'footer.creative': '// Creative Direction',
  'footer.tagline': '// unlike any other.',
  'footer.meta1': '// design system v2.0',
  'footer.meta2': '// april · 2026',
  'footer.meta3': '// São Paulo · Brasil',
  'page.footer.line': '// Bicofino Design System v2.0 — São Paulo, SP, Brasil — April 2026',

  // Performance Intelligence
  'perf.eyebrow': '// 05 · Motion — Performance Intelligence',
  'perf.title': 'Performance Intelligence',
  'perf.lead': 'A living visualization of the Bicofino OS system. Each number represents real efficiency — time recovered, output amplified, cost eliminated. Metrics pulse to remind you the data is active, not static.',
  'perf.metrics.label': '// 05.1 · Alive Components',
  'perf.metrics.title': 'System Metrics',
  'perf.chart.label': '// 05.2 · System vs Traditional',
  'perf.chart.title': 'Bicofino OS vs. Traditional',
  'perf.chart.lead': 'The compounding advantage of Bicofino OS. The traditional line grows linearly — the Bicofino system grows exponentially. The area between them represents generated efficiency.',
  'perf.card1.label': 'Time Saved / Week',
  'perf.card1.desc': 'Per consultant',
  'perf.card2.label': 'Output Multiplier',
  'perf.card2.desc': 'vs. traditional workflow',
  'perf.card3.label': 'Cost Reduction',
  'perf.card3.desc': 'Operational overhead',
  'perf.card4.label': 'Efficiency Gain',
  'perf.card4.desc': 'Year over year',
  'perf.card5.label': 'Active Agents',
  'perf.card5.desc': 'Running in parallel',
  'perf.card6.label': 'Response Time',
  'perf.card6.desc': 'Avg. system latency',

  // Icons
  'icons.eyebrow': '// 05.3 · Icons',
  'icons.title': 'Icons',
  'icons.lead': 'Icon system built on Lucide. Consistent stroke, single weight, predictable scale. Click any icon to copy the React snippet.',

  // On Field
  'onfield.eyebrow': '// 04 · On Field',
  'onfield.title': 'On Field — Athlete Image System',
  'onfield.intro.eyebrow': 'Image as presence. Data as proof.',
  'onfield.intro.lead': 'The On Field system treats the athlete as the main visual asset. Images are not placed inside generic cards — they create hierarchy, tension and presence. Data supports the narrative with precision.',
  'onfield.catalog.eyebrow': '// 04.2 · Asset Catalog',
  'onfield.catalog.title': 'On Field Asset Structure',
  'onfield.catalog.col.category': 'Category',
  'onfield.catalog.col.path': 'Folder path',
  'onfield.catalog.col.format': 'Format',
  'onfield.catalog.col.note': 'Usage note',
  'onfield.cat.portraits': 'Athlete Portraits',
  'onfield.cat.campaigns': 'Campaign Images',
  'onfield.cat.brand': 'Personal Brand',
  'onfield.cat.badges': 'Bicofino Badges',
  'onfield.cat.clubs': 'Club Shields',
  'onfield.cat.sponsors': 'Sponsor Logos',
  'onfield.cat.passports': 'Passports / Nations',
  'onfield.cat.venues': 'Venues',
  'onfield.cat.tournaments': 'Tournaments',
  'onfield.cat.icons': 'Performance Icons',
  'onfield.cat.portraits.note': 'Full-body or bust, white BG removed',
  'onfield.cat.campaigns.note': 'Editorial shoots, vertical preferred',
  'onfield.cat.brand.note': 'Wordmarks, monograms, personal logos',
  'onfield.cat.badges.note': 'Pro, FC, Day and event-specific badges',
  'onfield.cat.clubs.note': 'Official club crests, mono variant preferred',
  'onfield.cat.sponsors.note': 'Nike, Adidas, Puma — black/white versions',
  'onfield.cat.passports.note': 'Nationality flags as circular tokens',
  'onfield.cat.venues.note': 'Stadium silhouettes and locations',
  'onfield.cat.tournaments.note': 'Cup logos, competition marks',
  'onfield.cat.icons.note': 'Speed, body, pitch, trophy, sneaker, etc.',

  // Operations
  'ops.eyebrow': '// 06 · Operations',
  'ops.title': 'Operations',
  'ops.lead': 'Bicofino Group organizes its operations into two major verticals and one confidential project.',
  'ops.arch.label': '// 06.1',
  'ops.arch.title': 'Brand Architecture',
  'ops.onfield.title': 'ON FIELD',
  'ops.onfield.subtitle': '*Everything related to the athlete and their on-pitch performance*',
  'ops.onfield.desc': 'On Field brings together all services and specialists dedicated to the athlete as a performer. Doctors, physical performance specialists, nutritionists, sports psychologists, tactical coaches, data analysis technology — everything that maximizes the athlete on the pitch and ensures they reach the highest competitive level.',
  'ops.onfield.delivers.label': 'What On Field delivers:',
  'ops.onfield.d1': 'Athlete representation and management',
  'ops.onfield.d2': 'Physical, tactical, mental and cognitive development',
  'ops.onfield.d3': 'Performance and health monitoring',
  'ops.onfield.d4': 'Club contract management',
  'ops.onfield.d5': 'Positioning for international markets (Europe pipeline)',
  'ops.onfield.d6': 'Athlete media kit and profile for scouts and clubs',
  'ops.onfield.serves.label': 'Who it serves:',
  'ops.onfield.serves.desc': 'Bicofino portfolio athletes — primarily young football talents with international career potential.',
  'ops.offfield.title': 'OFF FIELD',
  'ops.offfield.subtitle': '*Everything that exists off the pitch*',
  'ops.offfield.desc': 'Off Field brings together all services that grow the athlete, brand or company beyond sports performance. This is also where Bicofino serves brands and companies — with or without a direct connection to athletes.',
  'ops.offfield.delivers.label': 'What Off Field delivers:',
  'ops.offfield.d1': 'Branding and visual identity (athletes, brands, companies)',
  'ops.offfield.d2': 'Advertising and content production',
  'ops.offfield.d3': 'Design, motion and art direction',
  'ops.offfield.d4': 'PR and executive personal branding',
  'ops.offfield.d5': 'Legal consulting and tax planning',
  'ops.offfield.d6': 'Family office and financial planning (Wealth)',
  'ops.offfield.d7': 'Connecting brands, companies, athletes and personalities',
  'ops.offfield.serves.label': 'Who it serves:',
  'ops.offfield.serves.desc': 'Portfolio athletes (off-pitch), brands seeking connection to the sports and premium universe, executives and companies looking for high-level creative and strategic curation.',
  'ops.offfield.diff.label': 'The Off Field differentiator:',
  'ops.offfield.diff.desc': 'Bicofino connects brands and companies to athletes, celebrities and personalities beyond the reach of most. This access was built over years of ethical relationships, clean negotiations and consistent presence in the right markets. Every connection is structured so all sides win.',
  'ops.club.title': 'CLUB',
  'ops.club.subtitle': '*Raposa Territory — confidential*',
  'ops.club.desc': 'The Club is Bicofino’s most intimate and selective project. Its profile, criteria and members are kept in complete discretion.',
  'ops.club.confidential': '*Details not publicly documented in this Brand System.*',
  'ops.visual.label': '// Visual architecture of verticals',
  'ops.visual.desc': 'On Field and Off Field share the same visual DNA — Inter, diamond ✦, core palette, reading hierarchy. What differentiates one from the other is the image universe:',
  'ops.visual.onfield': 'always images of athletes on the pitch, in training, in competition',
  'ops.visual.offfield': 'images of athletes in relation to brands, campaigns, companies and design — plus projects not involving athletes',
  'ops.delivery.label': '// 06.2',
  'ops.delivery.title': 'Delivery Standards',
  'ops.delivery.desc': 'All Bicofino output passes through the filter of 6 Operating Principles before delivery:',
  'ops.p1.title': 'Genuine obsession with detail',
  'ops.p1.desc': 'Is there something here that can be more precise?',
  'ops.p2.title': 'Beauty and intelligence in design',
  'ops.p2.desc': 'Is this delivery both beautiful and strategic?',
  'ops.p3.title': 'Deliver more than expected',
  'ops.p3.desc': 'Will the client notice they received beyond the brief?',
  'ops.p4.title': 'Simple, never simplistic',
  'ops.p4.desc': 'Is there something that can be cut without losing substance?',
  'ops.p5.title': 'Punch with elegance',
  'ops.p5.desc': 'Is the message clear and delivered with the right tone?',
  'ops.p6.title': 'Technology in service of creativity',
  'ops.p6.desc': 'Were AI and data used as amplifiers?',
  'ops.tools.label': '// Operation tools',
  'ops.tools.col.role': 'FUNCTION',
  'ops.tools.col.tool': 'TOOL',
  'ops.tool.memory.role': 'Memory',
  'ops.tool.memory.name': 'Google Drive + Supabase (database and local memory for agents)',
  'ops.tool.org.role': 'Organization',
  'ops.tool.org.name': 'Custom dashboard in development (no Notion)',
  'ops.tool.orch.role': 'Orchestration',
  'ops.tool.orch.name': 'Claude in terminal via Google Antigravity · AI agents in development and deployment',
  'ops.tool.intel.role': 'Intelligence / Strategy / Copy',
  'ops.tool.intel.name': 'Claude (primary) · ChatGPT · Gemini',
  'ops.tool.design.role': 'Design / Interface',
  'ops.tool.design.name': 'Photoshop · Illustrator · Claude Code (React, Tailwind, shadcn, Storybook)',
  'ops.tool.vi.role': 'Visual Identity',
  'ops.tool.vi.name': 'Adobe Suite',
  'ops.tool.video.role': 'Video Editing',
  'ops.tool.video.name': 'Adobe Premiere',
  'ops.tool.motion.role': 'Motion',
  'ops.tool.motion.name': 'Claude Code (components) · After Effects · Magnific',
  'ops.tool.imggen.role': 'Image Generation',
  'ops.tool.imggen.name': 'Magnific · Nano Banana · ChatGPT',
  'ops.tool.vidgen.role': 'Video Generation',
  'ops.tool.vidgen.name': 'Magnific · Google VEO',
  'ops.flow.label': '// Off Field delivery flow — Studio',
  'ops.flow.step1': 'Brief or demand intake (Friday preferred)',
  'ops.flow.step2': 'Production — 2 business days for recurring projects',
  'ops.flow.step3': 'Internal review — 1 business day',
  'ops.flow.step4': 'Client delivery',
  'ops.flow.step5': 'One revision round included in scope',
  'ops.flow.step6': 'Approval and archiving',
  'ops.commercial.label': '// Commercial policy',
  'ops.policy1': 'No discount on value. Adjustment via scope reduction, never quality.',
  'ops.policy2': 'Limited schedule. Waiting list when necessary.',
  'ops.policy3': 'Studio fees, media budget and production costs are separate, independent items.',
  'ops.policy4': 'All proposals in dossier format — never a price list or packages.',
  'ops.brand.line1': 'Brand System — Bicofino Group SA',
  'ops.brand.line2': 'Developed and maintained by Studio Bicofino',
  'ops.brand.line3': 'Woney Malian / Fabio Brancatelli',
  'ops.brand.version': 'v3.0 · São Paulo, BR · May 2026',
  'ops.brand.tagline': 'Unlike Any Other.',
} as const
