export const it = {
  // TopBar
  'topbar.title': 'Bicofino',
  'topbar.subtitle': 'Brand System',
  'topbar.version': 'V1.0',
  'topbar.date': '// maggio · 2026',

  // Overview
  'meta.eyebrow': '// DESIGN SYSTEM · V1.0',
  'overview.lead':
    'Il sistema di design del Bicofino Group organizza i fondamenti visivi, verbali e operativi che sostengono la sua presenza di marca. Creato per preservare coerenza estetica, chiarezza strategica e riconoscibilità in tutte le vertenti — senza sacrificare la velocità operativa.',
  'overview.meta.version': 'VERSIONE',
  'overview.meta.published': 'PUBBLICATO',
  'overview.meta.owner': 'OWNER',
  'overview.meta.base': 'BASE',
  'overview.meta.verticals': 'VERTICALI',
  'foundations.eyebrow': '// 02.1 · Universo Visivo',
  'foundations.title': 'Universo Visivo',
  'foundations.lead':
    "L'universo visivo di Bicofino opera su quattro qualità costanti e sempre presenti — in ogni comunicazione, di ogni vertente, in qualsiasi formato.",

  // Colors
  'colors.title': 'Tavolozza dei Colori',
  'colors.lead':
    'Colori strutturali che definiscono l\'identità Bicofino. Palette contenuta — poche tinte, ben applicate. Risalti usati con massima moderazione.',
  'colors.basics.title': 'Colori Base',
  'colors.specials.title': 'Colori Speciali',
  'colors.highlights.label': '// 02.2.3 · max 10% della superficie',
  'colors.highlights.title': 'Risalti',
  'colors.tokens.title': 'Color Tokens',
  'color.black.role': '// base · testo · wordmark',
  'color.steel.role': '// neutro · meta · captions',
  'color.aluminium.role': '// neutro · surface',
  'color.platinum.role': '// neutro · muted',
  'color.bg.role': '// surface · sfondo predefinito',
  'color.black.desc': 'Testi, bordi, elementi UI.',
  'color.steel.desc': 'Metadati, captions, icone secondarie.',
  'color.aluminium.desc': 'Superfici secondarie, hover, chip.',
  'color.platinum.desc': 'Accenti sottili, muted-foreground.',
  'color.bg.desc': 'Sfondo predefinito del sistema.',
  'color.white.role': '// surface · cards · elevazione',
  'color.white.desc': 'Cards, popover, superfici elevate.',
  'color.powerblack.role': '// profondità massima · dark',
  'color.powerblack.desc': 'Sfondo dark, massimo contrasto.',
  'color.crema.role': '// fc bicofino',
  'color.caffe.role': '// fc bicofino',
  'color.champagne.role': '// champagne',
  'color.cacao.role': '// terroso · lab',
  'token.black.role': 'Testi, wordmark, bordi, elementi UI',
  'token.powerblack.role': 'Sfondo dark, massimo contrasto',
  'token.bg.role': 'Sfondo predefinito del sistema',
  'token.white.role': 'Cards, popover, superfici elevate',
  'token.steel.role': 'Metadati, captions, icone',
  'token.aluminium.role': 'Superfici secondarie, hover, chip',
  'token.platinum.role': 'Muted foreground, accenti sottili',
  'token.crema.role': 'FC Bicofino — superficie calda',
  'token.caffe.role': 'FC Bicofino — scuro caldo',
  'token.cacao.role': 'Accento LAB — terroso, artigianale',
  'token.torino.role': 'Risalto editoriale — accento principale',
  'token.como.role': 'Risalto alternativo — accento freddo',
  'token.spfc.role': 'Risalto ADS — max 10% della superficie',
  'table.col.token': 'TOKEN',
  'table.col.value': 'VALORE',
  'table.col.name': 'NOME',
  'table.col.role': 'RUOLO',

  // Typography
  'typography.title': 'Tipografia',
  'typography.lead':
    'Inter per il testo editoriale e UI. JetBrains Mono per metadati, eyebrow e codice. Scala chiusa — nessuna dimensione fuori dal sistema.',
  'font.inter.subtitle': 'Google Fonts · SIL Open Font License',
  'font.inter.family': 'Sans-serif editoriale',
  'font.inter.weights': '400 · 500 · 600 · 700',
  'font.inter.coverage': '~95% del sistema',
  'font.inter.usage': 'Titoli, body, UI',
  'font.inter.license': 'SIL Open Font License',
  'font.mono.subtitle': 'Philipp Nurullin · JetBrains · Google Fonts',
  'font.mono.family': 'Monospaced',
  'font.mono.weights': '400 · 500',
  'font.mono.coverage': '~5% del sistema',
  'font.mono.usage': 'Metadati, eyebrow, codice',
  'font.mono.license': 'SIL Open Font License',
  'font.gotham.subtitle': 'Hoefler & Co. · self-hosted · solo impatto',
  'font.gotham.family': 'Geometrica · impatto',
  'font.gotham.weights': '300 · 500 · 700 · 900 (+ corsivi)',
  'font.gotham.coverage': '<1% — 1 o 2 parole',
  'font.gotham.usage': 'Nomi di atleti, titoli di post (maiuscolo)',
  'font.gotham.license': 'Commerciale · licenza Bicofino',
  'font.meta.family': 'Famiglia',
  'font.meta.weights': 'Pesi',
  'font.meta.coverage': 'Copertura',
  'font.meta.usage': 'Utilizzo',
  'font.meta.license': 'Licenza',
  'typescale.eyebrow.specimen': '// Sezione / Categoria',
  'typescale.eyebrow.meta': '11 mono · 0.16em · 600 · uppercase',

  // Heading
  'slash.title': 'Heading',
  'slash.what.title': "Cos'è",
  'slash.what.p1':
    "L'Heading è il titolo di apertura di ogni pagina o sezione principale del sistema Bicofino. Una dichiarazione tipografica breve, diretta e senza ornamenti — parole scelte che reggono il peso di un hero senza bisogno di una frase completa.",
  'slash.what.p2':
    'Il modello di riferimento è "Connect. Curate. Create. Consult." — quattro parole, quattro punti, impatto immediato. Nessun verbo esplicito. Nessuna spiegazione. Il titolo non presenta il contenuto — è il contenuto.',
  'slash.principles.title': 'Principi',
  'slash.principle.short': 'Breve.',
  'slash.principle.short.desc': 'Ogni parola ha peso. Il titolo hero non è mai una frase — è una posizione.',
  'slash.principle.direct': 'Diretto.',
  'slash.principle.direct.desc': 'Nessun qualificatore, nessuna subordinata, nessun gergo. Se richiede spiegazione, non è un heading.',
  'slash.principle.categorical': 'Categorico.',
  'slash.principle.categorical.desc': 'Afferma. Non interroga mai, non condiziona, non promette.',
  'slash.principle.singular': 'Singolare.',
  'slash.principle.singular.desc': 'Uno per pagina, uno per sezione. Mai impilato o ripetuto nella stessa composizione.',
  'slash.typo.title': 'Specifiche tipografiche',
  'slash.typo.col.element': 'Elemento',
  'slash.typo.col.type': 'Tipografia',
  'slash.typo.col.color': 'Colore',
  'slash.typo.row1': 'Heading principale',
  'slash.typo.row2': 'Heading su sfondo scuro',
  'slash.typo.note':
    "Dimensione determinata dalla scala chiusa — display-xl (96px) per gli hero di pagina, h1 (44px) per l'apertura di sezione. Mai fuori scala.",
  'slash.examples.title': 'Esempi',
  'slash.examples.col.heading': 'Heading',
  'slash.examples.col.context': 'Contesto',
  'slash.ex1.context': 'Posizionamento — i 4 C',
  'slash.ex2.context': 'Tagline come heading di apertura',
  'slash.ex3.context': 'Presentazione dei verticali',
  'slash.ex4.context': 'Apertura del Design System',
  'slash.ex5.context': 'Hero di sezione connessioni',
  'slash.ex6.context': 'Media kit — identificazione atleta',
  'slash.rejected.title': 'Esempi rifiutati',
  'slash.rejected.col.proposal': 'Proposta',
  'slash.rejected.col.problem': 'Problema',
  'slash.rej1.proposal': '"Innovazione per il futuro dello sport"',
  'slash.rej1.problem': 'Frase completa con gergo — non è un heading',
  'slash.rej2.proposal': '"The Best Creative Studio In São Paulo"',
  'slash.rej2.problem': 'Superlativo vuoto',
  'slash.rej3.proposal': '"Connettendo brand ad atleti di alto livello"',
  'slash.rej3.problem': 'Gerundio esplicativo — testo corpo, non titolo',
  'slash.rej4.proposal': '"Strategia · Creatività · Design · Esecuzione · Risultati"',
  'slash.rej4.problem': 'Troppo lungo — perde impatto',
  'slash.rej5.proposal': '"Cosa facciamo per te?"',
  'slash.rej5.problem': 'Interrogazione — Bicofino afferma, non chiede mai',
  'slash.where.title': 'Dove appare',
  'slash.where.item1': 'Hero di pagina e apertura di sezione nel sito e nel Brand System',
  'slash.where.item2': 'Copertina e apertura di presentazioni e dossier',
  'slash.where.item3': 'Headline dei media kit degli atleti',
  'slash.where.item4': 'Momenti di apertura in campagne e Bicofino Inspired',
  'slash.where.note':
    "Nel corpo del testo, nelle didascalie, nelle proposte correnti e nel copy dei social, Bicofino scrive in prosa diretta. L'heading esiste solo nei contesti sopra indicati — qualsiasi uso decorativo al di fuori di essi ne diluisce l'impatto.",

  // Spacing & Motion
  'spacing.title': 'Spaziatura & Motion',
  'spacing.lead':
    'Scala basata su multipli di 4px. Motion quieto, breve e lineare — senza overshoot, senza bounce.',
  'spacing.section.title': 'Spaziatura',
  'motion.section.title': 'Motion',
  'radius.section.title': 'Border Radius',
  'spacing.col.token': 'TOKEN',
  'spacing.col.px': 'PX',
  'spacing.col.rem': 'REM',
  'spacing.col.usage': 'USO TIPICO',
  'spacing.col.visual': 'VISUALE',
  'sp1.uso': 'micro-gap inline',
  'sp2.uso': 'icona ↔ label',
  'sp3.uso': 'padding piccolo',
  'sp4.uso': 'padding base',
  'sp5.uso': 'grid gutter',
  'sp6.uso': 'sezione compatta',
  'sp7.uso': 'tra sottosezioni',
  'sp8.uso': 'section padding',
  'sp9.uso': 'section padding · display',
  'radius.label.sm': 'sm',
  'radius.label.md': 'md',
  'radius.label.lg': 'lg',

  // Brand — Logo
  'brand.logo.title': 'Logotipo',
  'brand.logo.lead':
    'Il logotipo Bicofino è la firma primaria del brand. Sempre vettoriale, sempre in una delle versioni approvate di seguito.',
  'brand.logo.light': '// versione principale · su sfondo chiaro',
  'brand.logo.dark': '// versione inversa · su sfondo scuro',
  'brand.logo.crema': '// su crema · fc bicofino',
  'brand.logo.aluminium': '// su aluminium',
  'brand.logo.sizes.label': '// studio dimensioni · logotipo',
  'brand.logo.sizes.display': 'display',
  'brand.logo.sizes.padrao': 'standard',
  'brand.logo.sizes.compacto': 'compatto',
  'brand.logo.sizes.minimo': 'minimo',
  'brand.logo.sizes.evitar': 'evitare',
  'brand.logo.minrec': '// minimo raccomandato: 48px di larghezza',
  'brand.logo.rules.label': '// regole',
  'brand.logo.rule1': 'Non distorcere, ruotare o alterare le proporzioni.',
  'brand.logo.rule2': 'Mantenere uno spazio di protezione minimo pari all\'altezza della "B".',
  'brand.logo.rule3': 'Usare solo le versioni approvate — nero, bianco, o caffè su crema.',
  'brand.logo.rule4': 'Non applicare effetti, gradienti o ombre.',
  'brand.diamond.label': '// Diamante',
  'brand.diamond.lead':
    'Il simbolo isolato del brand. La stella a quattro punte ✦ — quattro assi di precisione, equilibrio, brillantezza contenuta. Il Diamond porta visivamente la stessa metafora del nome: il bico fino che filtra, che permette il passaggio solo di ciò che lo merita. Quattro punte convergenti in un centro esatto — curatela con forma.',
  'brand.diamond.lead2': 'Usato come marchio standalone quando il logotipo completo non entra o non è necessario.',
  'brand.diamond.light': '// su sfondo chiaro',
  'brand.diamond.dark': '// su sfondo scuro',
  'brand.diamond.crema': '// su crema · fc bicofino',
  'brand.diamond.aluminium': '// su aluminium',
  'brand.diamond.sizes.label': '// studio dimensioni · diamante',
  'brand.diamond.minrec': '// minimo raccomandato: 20px',

  // Voice & Tone
  'voice.title': 'Voce & Tono',
  'voice.lead':
    'La comunicazione Bicofino è diretta, precisa e sicura. Mai generica. Parla con autorità senza arroganza — come chi conosce il proprio lavoro.',
  'voice.direct.label': 'Diretto',
  'voice.direct.desc': 'Senza fronzoli. Una frase, un\'idea. Niente gergo inutile.',
  'voice.confident.label': 'Sicuro',
  'voice.confident.desc': 'Afferma. Non "forse", non "probabilmente". Quando parla, sa cosa dice.',
  'voice.editorial.label': 'Editoriale',
  'voice.editorial.desc': 'Tono curato. Parole scelte. Ritmo proprio — Lead / Slash / Echo.',
  'voice.nocliches.label': 'Senza cliché',
  'voice.nocliches.desc': 'Mai "innovativo", "dirompente", "all\'avanguardia". Parole vuote.',
  'voice.bilingual.label': 'Multilingue',
  'voice.bilingual.desc': 'Portoghese brasiliano come lingua principale. Inglese e italiano quando necessario.',

  // Verticais
  'verticais.title': 'Verticali',
  'verticais.lead':
    'Il Bicofino Group opera su due fronti editoriali. Ognuno ha la propria espressione visiva, all\'interno del sistema.',
  'verticais.onfield.desc':
    'Calcio. Competizione. Risultati. Comunicazione ad alta intensità — risalti visivi, colori di programma, urgenza editoriale.',
  'verticais.offfield.desc':
    'Lifestyle. Cultura. Stile di vita premium. Comunicazione editoriale sofisticata — quiet luxury, spazio bianco, tipografia, moderazione.',

  // Components — Buttons
  'buttons.title': 'Pulsanti',
  'buttons.lead':
    'Componenti costruiti dai token. Gerarchia tramite peso e contrasto — non tramite dimensione del bordo o colore extra.',
  'buttons.primary.label': '// Primary · Ghost · Link',
  'buttons.inverse.label': '// Inverse · su sfondo scuro',
  'btn.start': 'Avvia progetto',
  'btn.playbook': 'Vedi playbook',
  'btn.brand': 'brand.json →',
  'btn.manifesto': 'Vedi manifesto',
  'btn.case': 'Apri case',
  'btn.class.primary': '.btn-primary',
  'btn.class.ghost': '.btn-ghost',
  'btn.class.link': '.btn-link',
  'btn.class.primary.desc': '// sfondo bf Black',
  'btn.class.ghost.desc': '// bordo + fill on hover',
  'btn.class.link.desc': '// inline editoriale',
  'btn.inverse.class': '.btn-ghost.inverse',
  'btn.inverse.desc': '// su sfondo scuro',

  // Components — Badges
  'badges.title': 'Badges',
  'badges.lead':
    'Etichette di stato e categoria. Sempre monocromatiche all\'interno del sistema base — colore di programma solo in contesto ADS.',

  // Components — Forms
  'forms.title': 'Moduli',
  'forms.lead':
    'Gerarchia chiara tra label, input e helper text. Attrito minimo. Gli stati di errore usano il colore con parsimonia — preferire messaggi inline.',
  'form.name': 'Nome',
  'form.email': 'Email',
  'form.message': 'Messaggio',
  'form.message.placeholder': 'Scrivi qui...',
  'form.website': 'Sito web',
  'form.website.error': 'URL non valido. Includi https://',
  'form.access': 'Codice di accesso',
  'form.access.helper': 'Campo disabilitato.',

  // Components — Cards
  'cards.title': 'Cards',
  'cards.lead': 'Cards editoriali. Usate per evidenziare contenuti con gerarchia chiara.',
  'card.onfield.tag': 'Risultato',
  'card.onfield.title': 'Bicofino FC 3–1 Rival FC',
  'card.onfield.meta': 'Campionato · Giornata 12',
  'card.offfield.tag': 'Editoriale',
  'card.offfield.title': "L'arte della collezione capsule",
  'card.offfield.meta': 'Lifestyle · Aprile 2026',
  'card.ads.tag': 'Campagna',
  'card.ads.title': 'Brief campagna — Q2',
  'card.ads.meta': 'ADS · Kick-off maggio',

  // Governance
  'governance.title': 'Versione & Owners',
  'governance.lead':
    'Ogni layer del sistema ha un responsabile chiaro. Le modifiche ai Foundations richiedono la revisione degli owner. Componenti e Pattern possono essere proposti da qualsiasi membro del team.',
  'governance.col.layer': 'LAYER',
  'governance.col.owner': 'OWNER',
  'governance.col.scope': 'SCOPE',
  'governance.foundations.scope': 'Token, tipografia, palette, grid',
  'governance.brand.scope': 'Wordmark, voce, verticali',
  'governance.components.scope': 'Pattern UI, codice React/CSS',
  'governance.governance.scope': 'Versione, changelog, file',

  // Resources
  'resources.title': 'Risorse',
  'resources.col.file': 'FILE',
  'resources.col.purpose': 'SCOPO',
  'resource.tokens.css': 'CSS custom properties — fonte di verità per i token',
  'resource.tokens.ts': 'Costanti TypeScript — stessi token, tipizzati',
  'resource.globals.css': 'CSS base completo — token + stili base',
  'resource.design.md': 'Manuale di Identità Visiva — fonte editoriale di verità',
  'resource.claude.md': 'Istruzioni per agenti AI',
  'resource.storybook': 'Componenti interattivi — laboratorio tecnico',
  'resource.docs.site': 'Questo sito — documentazione editoriale premium',
  'resource.design.system': 'Token condivisi tra tutte le app',

  // Sidebar
  'nav.group.foundations': '// 02 · Design System',
  'nav.overview': 'Overview',
  'nav.bs.cover': 'Brand System',
  'nav.indice': 'Indice',
  'nav.fundamentos': 'Fondamenti',
  'nav.posicionamento': 'Posizionamento',
  'nav.nucleo': 'Nucleo del Brand',
  'nav.verbal': 'Universo Verbale',
  'nav.universo': 'Universo Visivo',
  'nav.colors': 'Colori',
  'nav.typography': 'Tipografia',
  'nav.slash': 'Heading',
  'nav.spacing': 'Spaziatura & Motion',
  'nav.group.brand': '// 03 · Brand',
  'nav.logo': 'Logotipo',
  'nav.voice': 'Voce & Tono',
  'nav.verticais': 'Verticali',
  'nav.onfield.img': 'On Pitch — Sistema Immagini',
  'nav.group.components': '// 04 · Componenti',
  'nav.buttons': 'Pulsanti',
  'nav.badges': 'Badges',
  'nav.forms': 'Moduli',
  'nav.cards': 'Cards',
  'nav.group.operacoes': '// 07 · Operazioni',
  'nav.operacoes': 'Architettura di Marca',
  'nav.delivery': 'Standard di Consegna',
  'nav.group.governance': '// 08 · Governance',
  'nav.governance': 'Versione & Owners',
  'nav.resources': 'Risorse',
  'nav.group.performance': '// 06 · Asset',
  'nav.performance': 'Motion Intelligence',
  'nav.sponsors': 'Sponsors',
  'nav.icons': 'Icone',
  'sidebar.tagline': '// unlike any other.',
  'sidebar.version': '// v1.0 · aprile 2026',
  'sidebar.location': '// São Paulo · BR',

  // Footer
  'footer.system': '// Sistema',
  'footer.system.value': 'Foundations · Brand · Componenti · Governance',
  'footer.docs': '// Documenti',
  'footer.docs.value': 'DESIGN.md · tokens.css · tokens.ts · README',
  'footer.verticals': '// Verticali',
  'footer.verticals.value': 'On Pitch · Off Pitch',
  'footer.creative': '// Direzione Creativa',
  'footer.tagline': '// unlike any other.',
  'footer.meta1': '// design system v1.0',
  'footer.meta2': '// aprile · 2026',
  'footer.meta3': '// São Paulo · Brasil',
  'page.footer.line': '// Bicofino Design System v1.0 — São Paulo, SP, Brasil — Aprile 2026',

  // Performance Intelligence
  'perf.eyebrow': '// 06.1 · Motion Intelligence',
  'perf.title': 'Performance Intelligence',
  'perf.lead': 'Una visualizzazione viva del sistema Bicofino OS. Ogni numero rappresenta efficienza reale — tempo recuperato, output amplificato, costi eliminati. Le metriche pulsano per ricordare che i dati sono attivi, non statici.',
  'perf.metrics.label': '// 06.1.1 · Alive Components',
  'perf.metrics.title': 'Metriche del Sistema',
  'perf.chart.label': '// 06.1.2 · Sistema vs Tradizionale',
  'perf.chart.title': 'Bicofino OS vs. Tradizionale',
  'perf.chart.lead': "Il vantaggio composto di Bicofino OS. La linea tradizionale cresce linearmente — il sistema Bicofino cresce esponenzialmente. L'area tra esse rappresenta l'efficienza generata.",
  'perf.card1.label': 'Tempo Risparmiato / Settimana',
  'perf.card1.desc': 'Per consulente',
  'perf.card2.label': 'Moltiplicatore di Output',
  'perf.card2.desc': 'vs. flusso tradizionale',
  'perf.card3.label': 'Riduzione dei Costi',
  'perf.card3.desc': 'Overhead operativo',
  'perf.card4.label': 'Guadagno di Efficienza',
  'perf.card4.desc': 'Anno su anno',
  'perf.card5.label': 'Agenti Attivi',
  'perf.card5.desc': 'In parallelo',
  'perf.card6.label': 'Tempo di Risposta',
  'perf.card6.desc': 'Latenza media del sistema',

  // Sponsors
  'sponsors.eyebrow': '// 06.2 · Sponsors',
  'sponsors.title': 'Sponsor',
  'sponsors.lead': 'Marchi globali e aziende di riferimento con cui Bicofino mantiene relazioni strette — costruite con accesso, fiducia e contesto strategico accumulati nel tempo.',

  // Icons
  'icons.eyebrow': '// 06.3 · Icons',
  'icons.title': 'Icone',
  'icons.lead': 'Sistema di icone basato su Lucide. Tratto consistente, peso singolo, scala prevedibile. Clicca su qualsiasi icona per copiare lo snippet React.',

  // On Pitch
  'onfield.eyebrow': '// 05.2 · On Pitch — Image System',
  'onfield.title': 'On Pitch — Sistema Immagini Atleti',
  'onfield.intro.eyebrow': 'Immagine come presenza. Dati come prova.',
  'onfield.intro.lead': "Il sistema On Pitch tratta l'atleta come il principale asset visivo. Le immagini non vengono inserite in card generiche — creano gerarchia, tensione e presenza. I dati sostengono la narrazione con precisione.",
  'onfield.catalog.eyebrow': '// 05.2.2 · Asset Catalog',
  'onfield.catalog.title': 'Struttura Asset On Pitch',
  'onfield.catalog.col.category': 'Categoria',
  'onfield.catalog.col.path': 'Cartella',
  'onfield.catalog.col.format': 'Formato',
  'onfield.catalog.col.note': 'Nota',
  'onfield.cat.portraits': 'Ritratti Atleti',
  'onfield.cat.campaigns': 'Immagini Campagna',
  'onfield.cat.brand': 'Brand Personale',
  'onfield.cat.badges': 'Badges Bicofino',
  'onfield.cat.clubs': 'Stemmi Club',
  'onfield.cat.sponsors': 'Loghi Sponsor',
  'onfield.cat.passports': 'Passaporti / Nazioni',
  'onfield.cat.venues': 'Stadi',
  'onfield.cat.tournaments': 'Tornei',
  'onfield.cat.icons': 'Icone di Performance',
  'onfield.cat.portraits.note': 'Corpo intero o busto, sfondo bianco rimosso',
  'onfield.cat.campaigns.note': 'Shooting editoriali, verticale preferito',
  'onfield.cat.brand.note': 'Wordmark, monogrammi, loghi personali',
  'onfield.cat.badges.note': 'Pro, FC, Day e badge per eventi specifici',
  'onfield.cat.clubs.note': 'Stemmi ufficiali, variante mono preferita',
  'onfield.cat.sponsors.note': 'Nike, Adidas, Puma — versioni bianco/nero',
  'onfield.cat.passports.note': 'Bandiere di nazionalità come token circolari',
  'onfield.cat.venues.note': 'Silhouette di stadi e location',
  'onfield.cat.tournaments.note': 'Loghi di coppe, marchi di competizione',
  'onfield.cat.icons.note': 'Velocità, corpo, campo, trofeo, scarpa, ecc.',

  // Operations
  'ops.eyebrow': '// 07 • OPERAZIONI',
  'ops.title': 'Operazioni',
  'ops.lead': 'Il Bicofino Group organizza le proprie operazioni in due grandi verticali e un progetto riservato.',
  'ops.arch.label': '// 07.1',
  'ops.arch.title': 'Architettura di Marca',
  'ops.onfield.title': 'ON PITCH',
  'ops.onfield.subtitle': '*Tutto relativo all\'atleta e alla sua performance in campo*',
  'ops.onfield.desc': "On Pitch riunisce tutti i servizi e gli specialisti dedicati all'atleta come performer. Medici, specialisti in performance fisica, nutrizionisti, psicologi dello sport, coach tattici, tecnologia di analisi dei dati — tutto ciò che potenzia l'atleta in campo e garantisce che raggiunga il più alto livello di competizione.",
  'ops.onfield.delivers.label': 'Cosa consegna On Pitch:',
  'ops.onfield.d1': 'Procura e rappresentanza di atleti',
  'ops.onfield.d2': 'Sviluppo fisico, tattico, mentale e cognitivo',
  'ops.onfield.d3': 'Monitoraggio di performance e salute',
  'ops.onfield.d4': 'Gestione dei contratti con i club',
  'ops.onfield.d5': 'Posizionamento per mercati internazionali (pipeline Europa)',
  'ops.onfield.d6': 'Media kit e profilo atleta per scout e club',
  'ops.onfield.serves.label': 'Chi serve:',
  'ops.onfield.serves.desc': "Atleti del portfolio Bicofino — principalmente giovani talenti del calcio con potenziale di carriera internazionale.",
  'ops.offfield.title': 'OFF PITCH',
  'ops.offfield.subtitle': '*Tutto ciò che esiste fuori dal campo*',
  'ops.offfield.desc': "Off Pitch riunisce tutti i servizi che fanno crescere l'atleta, il brand o l'azienda oltre la performance sportiva. È anche qui che Bicofino serve brand e aziende — con o senza connessione diretta con gli atleti.",
  'ops.offfield.delivers.label': 'Cosa consegna Off Pitch:',
  'ops.offfield.d1': 'Branding e identità visiva (atleti, brand, aziende)',
  'ops.offfield.d2': 'Advertising e produzione di contenuti',
  'ops.offfield.d3': 'Design, motion e direzione artistica',
  'ops.offfield.d4': 'PR e personal branding esecutivo',
  'ops.offfield.d5': 'Consulenza legale e pianificazione fiscale',
  'ops.offfield.d6': 'Family office e pianificazione finanziaria (Wealth)',
  'ops.offfield.d7': 'Connessione tra brand, aziende, atleti e personalità',
  'ops.offfield.serves.label': 'Chi serve:',
  'ops.offfield.serves.desc': "Atleti del portfolio (extra-campo), brand che vogliono connessione con l'universo sportivo e premium, dirigenti e aziende in cerca di curatela creativa e strategica di alto livello.",
  'ops.offfield.diff.label': 'Il differenziale Off Pitch:',
  'ops.offfield.diff.desc': "Bicofino connette brand e aziende ad atleti, celebrità e personalità fuori dalla portata della grande maggioranza. Questo accesso è stato costruito con anni di relazioni etiche, negoziazioni trasparenti e presenza costante nei mercati giusti. Ogni connessione è strutturata affinché tutte le parti guadagnino.",
  'ops.club.title': 'CLUB',
  'ops.club.subtitle': '*Territorio della Raposa — riservato*',
  'ops.club.desc': 'Il Club è il progetto più intimo e selettivo di Bicofino. Il suo profilo, i criteri e i membri sono mantenuti in totale discrezione.',
  'ops.club.confidential': '*Dettagli non documentati pubblicamente in questo Brand System.*',
  'ops.visual.label': '// Architettura visiva delle verticali',
  'ops.visual.desc': 'On Pitch e Off Pitch condividono lo stesso DNA visivo — Inter, diamond ✦, palette core, gerarchia di lettura. Ciò che differenzia una dall\'altra è l\'universo delle immagini:',
  'ops.visual.onfield': 'sempre immagini di atleti in campo, in allenamento, in competizione',
  'ops.visual.offfield': 'immagini di atleti in relazione a brand, campagne, aziende e design — oltre a progetti che non coinvolgono atleti',
  'ops.delivery.label': '// 07.2',
  'ops.delivery.title': 'Standard di Consegna',
  'ops.delivery.desc': 'Ogni output di Bicofino passa attraverso il filtro dei 6 Principi Operativi prima di essere consegnato:',
  'ops.p1.title': 'Ossessione genuina per i dettagli',
  'ops.p1.desc': "C'è qualcosa qui che può essere più preciso?",
  'ops.p2.title': 'Bellezza e intelligenza nel design',
  'ops.p2.desc': 'Questa consegna è allo stesso tempo bella e strategica?',
  'ops.p3.title': 'Consegnare più del previsto',
  'ops.p3.desc': 'Il cliente si accorgerà di aver ricevuto più del brief?',
  'ops.p4.title': 'Semplice, mai semplicistico',
  'ops.p4.desc': "C'è qualcosa che può essere eliminato senza perdere sostanza?",
  'ops.p5.title': 'Forza con eleganza',
  'ops.p5.desc': 'Il messaggio è chiaro e consegnato con il tono giusto?',
  'ops.p6.title': 'Tecnologia al servizio della creatività',
  'ops.p6.desc': "L'AI e i dati sono stati usati come amplificatori?",
  'ops.tools.label': '// Strumenti operativi',
  'ops.tools.col.role': 'FUNZIONE',
  'ops.tools.col.tool': 'STRUMENTO',
  'ops.tool.memory.role': 'Memoria',
  'ops.tool.memory.name': 'Google Drive + Supabase (database e memoria locale per agenti)',
  'ops.tool.org.role': 'Organizzazione',
  'ops.tool.org.name': 'Dashboard proprietario in sviluppo (senza Notion)',
  'ops.tool.orch.role': 'Orchestrazione',
  'ops.tool.orch.name': 'Claude nel terminale via Google Antigravity · Agenti AI in sviluppo e implementazione',
  'ops.tool.intel.role': 'Intelligenza / Strategia / Copy',
  'ops.tool.intel.name': 'Claude (primario) · ChatGPT · Gemini',
  'ops.tool.design.role': 'Design / Interfaccia',
  'ops.tool.design.name': 'Photoshop · Illustrator · Claude Code (React, Tailwind, shadcn, Storybook)',
  'ops.tool.vi.role': 'Identità Visiva',
  'ops.tool.vi.name': 'Pacchetto Adobe',
  'ops.tool.video.role': 'Montaggio Video',
  'ops.tool.video.name': 'Adobe Premiere',
  'ops.tool.motion.role': 'Motion',
  'ops.tool.motion.name': 'Claude Code (componenti) · After Effects · Magnific',
  'ops.tool.imggen.role': 'Generazione di Immagini',
  'ops.tool.imggen.name': 'Magnific · Nano Banana · ChatGPT',
  'ops.tool.vidgen.role': 'Generazione di Video',
  'ops.tool.vidgen.name': 'Magnific · Google VEO',
  'ops.flow.label': '// Flusso di consegna Off Pitch — Studio',
  'ops.flow.step1': 'Brief o ricezione della richiesta (preferibilmente il venerdì)',
  'ops.flow.step2': 'Produzione — 2 giorni lavorativi per progetti ricorrenti',
  'ops.flow.step3': 'Revisione interna — 1 giorno lavorativo',
  'ops.flow.step4': 'Consegna al cliente',
  'ops.flow.step5': 'Un round di revisione incluso nello scope',
  'ops.flow.step6': 'Approvazione e archiviazione',
  'ops.commercial.label': '// Politica commerciale',
  'ops.policy1': 'Nessuno sconto sul valore. Adeguamento tramite riduzione dello scope, mai della qualità.',
  'ops.policy2': 'Agenda limitata. Lista d\'attesa quando necessario.',
  'ops.policy3': 'Onorari dello Studio, budget media e costi di produzione sono voci separate e indipendenti.',
  'ops.policy4': 'Ogni proposta in formato dossier — mai listino prezzi o pacchetti.',
  'ops.brand.line1': 'Brand System — Bicofino Group SA',
  'ops.brand.line2': 'Elaborato e mantenuto dallo Studio Bicofino',
  'ops.brand.line3': 'Woney Malian / Fabio Brancatelli',
  'ops.brand.version': 'v1.0 · São Paulo, BR · Maggio 2026',
  'ops.brand.tagline': 'Unlike Any Other.',
} as const
