export const cornerLanguagesI18n = {
  br: {
    'corners.eyebrow':              '// 02 · Sistema Visual · D2',
    'corners.title':                'Linguagens de Canto',
    'corners.lead':                 'Uma peça escolhe um idioma de canto — e mantém essa escolha. O que unifica o trabalho do Bicofino é limpeza, cor, alinhamento e espaçamento, não o raio. O canto é uma variável livre; a coerência vem dos invariantes.',
    'corners.switch.note':          'Componentes leem a escala comutável via',
    'corners.switch.attr':          'data-corners="soft"',
    'corners.switch.suffix':        'em qualquer contêiner pai.',

    'corners.sharp.name':           'Sharp',
    'corners.sharp.tag':            'cartesiano · ordem · padrão',
    'corners.sharp.desc':           'Para dossiês, dados e temas técnicos — qualquer coisa que deva parecer precisa e organizada.',
    'corners.sharp.1.label':        '--bf-sharp-1',
    'corners.sharp.1.value':        '2px',
    'corners.sharp.2.label':        '--bf-sharp-2',
    'corners.sharp.2.value':        '4px',
    'corners.sharp.3.label':        '--bf-sharp-3',
    'corners.sharp.3.value':        '8px',

    'corners.soft.name':            'Soft',
    'corners.soft.tag':             'circular · movimento · carrossel',
    'corners.soft.desc':            'Para carrosséis e temas de movimento — um jogador fazendo a bola e o time girar; peças que devem parecer fluidas.',
    'corners.soft.1.label':         '--bf-soft-1',
    'corners.soft.1.value':         '12px',
    'corners.soft.2.label':         '--bf-soft-2',
    'corners.soft.2.value':         '18px',
    'corners.soft.3.label':         '--bf-soft-3',
    'corners.soft.3.value':         '28px',

    'corners.pill.label':           'PILL · 9999',
    'corners.pill.note':            'Pills e avatares são completamente arredondados em ambas as linguagens, sempre.',

    'corners.live.section':         'Demonstração ao vivo',
    'corners.live.sharp.label':     'Contêiner Sharp',
    'corners.live.sharp.card':      'Cartão',
    'corners.live.sharp.badge':     'Distintivo',
    'corners.live.soft.label':      'Contêiner Soft',
    'corners.live.soft.card':       'Cartão',
    'corners.live.soft.badge':      'Distintivo',
    'corners.live.note':            'Ambos os contêineres acima usam os mesmos componentes internos — apenas o atributo de canto do pai muda.',

    'corners.rule.title':           'A regra',
    'corners.rule.body':            'Uma peça, uma linguagem. Não misture sharp e soft no mesmo quadro. Pill é a exceção permanente — funciona nos dois.',
    'corners.rule.token':           '--bf-corner-1/2/3',
    'corners.rule.token.suffix':    'resolvem para o idioma ativo — nenhuma componente precisa codificar o raio de forma rígida.',
  },

  en: {
    'corners.eyebrow':              '// 02 · Visual System · D2',
    'corners.title':                'Corner Languages',
    'corners.lead':                 'A piece picks one corner language — and keeps it. What unifies Bicofino work is cleanliness, color, alignment, and spacing, not the radius. The corner is a free variable; coherence comes from the invariants.',
    'corners.switch.note':          'Components read the switchable scale via',
    'corners.switch.attr':          'data-corners="soft"',
    'corners.switch.suffix':        'on any parent container.',

    'corners.sharp.name':           'Sharp',
    'corners.sharp.tag':            'cartesian · order · default',
    'corners.sharp.desc':           'For dossiers, data, and technical themes — anything that should feel precise and organized.',
    'corners.sharp.1.label':        '--bf-sharp-1',
    'corners.sharp.1.value':        '2px',
    'corners.sharp.2.label':        '--bf-sharp-2',
    'corners.sharp.2.value':        '4px',
    'corners.sharp.3.label':        '--bf-sharp-3',
    'corners.sharp.3.value':        '8px',

    'corners.soft.name':            'Soft',
    'corners.soft.tag':             'circular · movement · carousel',
    'corners.soft.desc':            'For carousels and movement themes — a player making the ball and the team spin; pieces that should feel fluid.',
    'corners.soft.1.label':         '--bf-soft-1',
    'corners.soft.1.value':         '12px',
    'corners.soft.2.label':         '--bf-soft-2',
    'corners.soft.2.value':         '18px',
    'corners.soft.3.label':         '--bf-soft-3',
    'corners.soft.3.value':         '28px',

    'corners.pill.label':           'PILL · 9999',
    'corners.pill.note':            'Pills and avatars are full-round in both languages, always.',

    'corners.live.section':         'Live demo',
    'corners.live.sharp.label':     'Sharp container',
    'corners.live.sharp.card':      'Card',
    'corners.live.sharp.badge':     'Badge',
    'corners.live.soft.label':      'Soft container',
    'corners.live.soft.card':       'Card',
    'corners.live.soft.badge':      'Badge',
    'corners.live.note':            'Both containers above use the same inner components — only the parent\'s corner attribute changes.',

    'corners.rule.title':           'The rule',
    'corners.rule.body':            'One piece, one language. Do not mix sharp and soft in the same frame. Pill is the permanent exception — it works in both.',
    'corners.rule.token':           '--bf-corner-1/2/3',
    'corners.rule.token.suffix':    'resolve to the active language — no component needs to hard-code a radius.',
  },

  it: {
    'corners.eyebrow':              '// 02 · Sistema Visivo · D2',
    'corners.title':                'Linguaggi degli Angoli',
    'corners.lead':                 'Un pezzo sceglie un linguaggio per gli angoli — e lo mantiene. Ciò che unifica il lavoro Bicofino è pulizia, colore, allineamento e spaziatura, non il raggio. L\'angolo è una variabile libera; la coerenza viene dagli invarianti.',
    'corners.switch.note':          'I componenti leggono la scala commutabile tramite',
    'corners.switch.attr':          'data-corners="soft"',
    'corners.switch.suffix':        'su qualsiasi contenitore padre.',

    'corners.sharp.name':           'Sharp',
    'corners.sharp.tag':            'cartesiano · ordine · default',
    'corners.sharp.desc':           'Per dossier, dati e temi tecnici — qualsiasi cosa che debba sembrare precisa e organizzata.',
    'corners.sharp.1.label':        '--bf-sharp-1',
    'corners.sharp.1.value':        '2px',
    'corners.sharp.2.label':        '--bf-sharp-2',
    'corners.sharp.2.value':        '4px',
    'corners.sharp.3.label':        '--bf-sharp-3',
    'corners.sharp.3.value':        '8px',

    'corners.soft.name':            'Soft',
    'corners.soft.tag':             'circolare · movimento · carosello',
    'corners.soft.desc':            'Per caroselli e temi di movimento — un giocatore che fa girare il pallone e la squadra; pezzi che devono sembrare fluidi.',
    'corners.soft.1.label':         '--bf-soft-1',
    'corners.soft.1.value':         '12px',
    'corners.soft.2.label':         '--bf-soft-2',
    'corners.soft.2.value':         '18px',
    'corners.soft.3.label':         '--bf-soft-3',
    'corners.soft.3.value':         '28px',

    'corners.pill.label':           'PILL · 9999',
    'corners.pill.note':            'Pill e avatar sono completamente arrotondati in entrambi i linguaggi, sempre.',

    'corners.live.section':         'Demo in tempo reale',
    'corners.live.sharp.label':     'Contenitore Sharp',
    'corners.live.sharp.card':      'Scheda',
    'corners.live.sharp.badge':     'Distintivo',
    'corners.live.soft.label':      'Contenitore Soft',
    'corners.live.soft.card':       'Scheda',
    'corners.live.soft.badge':      'Distintivo',
    'corners.live.note':            'Entrambi i contenitori sopra usano gli stessi componenti interni — cambia solo l\'attributo degli angoli del padre.',

    'corners.rule.title':           'La regola',
    'corners.rule.body':            'Un pezzo, un linguaggio. Non mescolare sharp e soft nello stesso frame. Pill è l\'eccezione permanente — funziona in entrambi.',
    'corners.rule.token':           '--bf-corner-1/2/3',
    'corners.rule.token.suffix':    'risolvono al linguaggio attivo — nessun componente ha bisogno di codificare un raggio in modo rigido.',
  },
} as const
