export const postSystemI18n = {
  br: {
    'postsys.eyebrow':             '// 03 · Brand · M-04',
    'postsys.title':               'Post-System 60/40',
    'postsys.lead':                'Obras diferentes, mesma marca. A unidade vem de constantes repetidas — paleta, ✦, arco, nome em mono, recorte — não de um layout repetido. ~60% de respiro; uma zona preenchida simétrica contra uma vazia.',

    'postsys.grid.label':          'Grade de exemplos',
    'postsys.grid.desc':           'Cada post usa crema (claro) ou caffè (escuro), um vibrant único e os cinco invariantes. O layout interno pode variar — os constantes não.',

    'postsys.post1.name':          'GUI KERCHNER',
    'postsys.post1.date':          '14 JAN',
    'postsys.post2.name':          'JÚLIO CÉZAR',
    'postsys.post2.date':          'OUT',
    'postsys.post3.name':          'RONALDO',
    'postsys.post3.date':          '19 JAN',
    'postsys.post4.name':          'VINÍCIUS JR.',
    'postsys.post4.date':          'FEV',
    'postsys.post5.name':          'NEYMAR',
    'postsys.post5.date':          '07 MAR',
    'postsys.post6.name':          'PEDRI',
    'postsys.post6.date':          'ABR',

    'postsys.constants.label':     'Constantes do sistema',
    'postsys.constants.palette':   'paleta',
    'postsys.constants.diamond':   '✦ diamante',
    'postsys.constants.arc':       'arco / moldura',
    'postsys.constants.mono':      'nome em mono',
    'postsys.constants.cutout':    'recorte',

    'postsys.rule.label':          'A regra',
    'postsys.rule.60':             '60% respiro',
    'postsys.rule.60.desc':        'Espaço vazio intencional — não ausência de conteúdo, mas zona ativa de respiração.',
    'postsys.rule.40':             '40% zona preenchida',
    'postsys.rule.40.desc':        'Silhueta, nome, data e o ✦. Nada mais.',
    'postsys.rule.note':           'Um vibrant por composição, via --current-accent. Nunca dois.',

    'postsys.vocab.label':         'Vocabulário visual',
    'postsys.vocab.arc.name':      'Arco',
    'postsys.vocab.arc.desc':      'Gradiente radial repetido, opacidade 16%. Traz textura sem ruído.',
    'postsys.vocab.frame.name':    'Moldura',
    'postsys.vocab.frame.desc':    'Borda inset com inset 13px, opacidade 26%. Delimita sem prender.',
    'postsys.vocab.diamond.name':  '✦ Diamante',
    'postsys.vocab.diamond.desc':  'SVG centralizado no topo. Lacre de identidade.',
    'postsys.vocab.cutout.name':   'Recorte',
    'postsys.vocab.cutout.desc':   'Figura preenchida, 56% de largura, ancorada na base.',
    'postsys.vocab.mono.name':     'Nome em mono',
    'postsys.vocab.mono.desc':     'JetBrains Mono, 7.5px, caixa alta, 0.14em tracking. Abaixo da figura.',

    'page.footer.line':            '// Bicofino Design System v3.1 — São Paulo, SP, Brasil — 2026',
  },

  en: {
    'postsys.eyebrow':             '// 03 · Brand · M-04',
    'postsys.title':               'Post-System 60/40',
    'postsys.lead':                'Different artworks, same brand. Unity comes from repeated constants — palette, ✦, arc, mono name, cut-out — not a repeated layout. ~60% breathing; a symmetric filled zone against an empty one.',

    'postsys.grid.label':          'Example grid',
    'postsys.grid.desc':           'Each post uses crema (light) or caffè (dark), one single vibrant, and the five invariants. The internal layout may vary — the constants do not.',

    'postsys.post1.name':          'GUI KERCHNER',
    'postsys.post1.date':          '14 JAN',
    'postsys.post2.name':          'JÚLIO CÉZAR',
    'postsys.post2.date':          'OCT',
    'postsys.post3.name':          'RONALDO',
    'postsys.post3.date':          '19 JAN',
    'postsys.post4.name':          'VINÍCIUS JR.',
    'postsys.post4.date':          'FEB',
    'postsys.post5.name':          'NEYMAR',
    'postsys.post5.date':          '07 MAR',
    'postsys.post6.name':          'PEDRI',
    'postsys.post6.date':          'APR',

    'postsys.constants.label':     'System constants',
    'postsys.constants.palette':   'palette',
    'postsys.constants.diamond':   '✦ diamond',
    'postsys.constants.arc':       'arc / frame',
    'postsys.constants.mono':      'mono name',
    'postsys.constants.cutout':    'cut-out',

    'postsys.rule.label':          'The rule',
    'postsys.rule.60':             '60% breathing',
    'postsys.rule.60.desc':        'Intentional empty space — not absent content, but an active breathing zone.',
    'postsys.rule.40':             '40% filled zone',
    'postsys.rule.40.desc':        'Silhouette, name, date, and the ✦. Nothing more.',
    'postsys.rule.note':           'One vibrant per composition, via --current-accent. Never two.',

    'postsys.vocab.label':         'Visual vocabulary',
    'postsys.vocab.arc.name':      'Arc',
    'postsys.vocab.arc.desc':      'Repeated radial gradient, 16% opacity. Adds texture without noise.',
    'postsys.vocab.frame.name':    'Frame',
    'postsys.vocab.frame.desc':    'Inset border at 13px, 26% opacity. Delimits without confining.',
    'postsys.vocab.diamond.name':  '✦ Diamond',
    'postsys.vocab.diamond.desc':  'Centered SVG at the top. Identity seal.',
    'postsys.vocab.cutout.name':   'Cut-out',
    'postsys.vocab.cutout.desc':   'Filled figure, 56% width, anchored at the base.',
    'postsys.vocab.mono.name':     'Mono name',
    'postsys.vocab.mono.desc':     'JetBrains Mono, 7.5px, uppercase, 0.14em tracking. Below the figure.',

    'page.footer.line':            '// Bicofino Design System v3.1 — São Paulo, SP, Brasil — 2026',
  },

  it: {
    'postsys.eyebrow':             '// 03 · Brand · M-04',
    'postsys.title':               'Post-System 60/40',
    'postsys.lead':                'Opere diverse, stesso brand. L\'unità viene da costanti ripetute — palette, ✦, arco, nome in mono, ritaglio — non da un layout ripetuto. ~60% di respiro; una zona riempita simmetrica contro una vuota.',

    'postsys.grid.label':          'Griglia di esempi',
    'postsys.grid.desc':           'Ogni post usa crema (chiaro) o caffè (scuro), un unico vibrant e i cinque invarianti. Il layout interno può variare — le costanti no.',

    'postsys.post1.name':          'GUI KERCHNER',
    'postsys.post1.date':          '14 GEN',
    'postsys.post2.name':          'JÚLIO CÉZAR',
    'postsys.post2.date':          'OTT',
    'postsys.post3.name':          'RONALDO',
    'postsys.post3.date':          '19 GEN',
    'postsys.post4.name':          'VINÍCIUS JR.',
    'postsys.post4.date':          'FEB',
    'postsys.post5.name':          'NEYMAR',
    'postsys.post5.date':          '07 MAR',
    'postsys.post6.name':          'PEDRI',
    'postsys.post6.date':          'APR',

    'postsys.constants.label':     'Costanti del sistema',
    'postsys.constants.palette':   'palette',
    'postsys.constants.diamond':   '✦ diamante',
    'postsys.constants.arc':       'arco / cornice',
    'postsys.constants.mono':      'nome in mono',
    'postsys.constants.cutout':    'ritaglio',

    'postsys.rule.label':          'La regola',
    'postsys.rule.60':             '60% respiro',
    'postsys.rule.60.desc':        'Spazio vuoto intenzionale — non assenza di contenuto, ma zona attiva di respirazione.',
    'postsys.rule.40':             '40% zona riempita',
    'postsys.rule.40.desc':        'Silhouette, nome, data e il ✦. Nient\'altro.',
    'postsys.rule.note':           'Un vibrant per composizione, tramite --current-accent. Mai due.',

    'postsys.vocab.label':         'Vocabolario visivo',
    'postsys.vocab.arc.name':      'Arco',
    'postsys.vocab.arc.desc':      'Gradiente radiale ripetuto, opacità 16%. Aggiunge texture senza rumore.',
    'postsys.vocab.frame.name':    'Cornice',
    'postsys.vocab.frame.desc':    'Bordo inset a 13px, opacità 26%. Delimita senza imprigionare.',
    'postsys.vocab.diamond.name':  '✦ Diamante',
    'postsys.vocab.diamond.desc':  'SVG centrato in alto. Sigillo di identità.',
    'postsys.vocab.cutout.name':   'Ritaglio',
    'postsys.vocab.cutout.desc':   'Figura riempita, 56% di larghezza, ancorata alla base.',
    'postsys.vocab.mono.name':     'Nome in mono',
    'postsys.vocab.mono.desc':     'JetBrains Mono, 7.5px, maiuscolo, tracking 0.14em. Sotto la figura.',

    'page.footer.line':            '// Bicofino Design System v3.1 — São Paulo, SP, Brasil — 2026',
  },
} as const
