export const br = {
  // Site
  'site.title': 'Bicofino Design Studio',
  'site.description': 'Sistema visual e de marca — referência completa de componentes e diretrizes.',

  // UI controls
  'ui.theme.toggle': 'Alternar tema',
  'ui.lang.label': 'Idioma',
  'ui.menu.open': 'Abrir menu',
  'ui.menu.close': 'Fechar menu',

  // Language labels
  'lang.br': 'Português',
  'lang.en': 'English',
  'lang.it': 'Italiano',

  // Nav groups (match navigation.ts titles)
  'nav.brand-system': 'Brand System',
  'nav.visual-system': 'Visual System',
  'nav.components': 'Components',
  'nav.verticais': 'Verticais',
  'nav.assets': 'Assets',
  'nav.operacoes': 'Operações',
  'nav.governanca': 'Governança',

  // Nav items
  'nav.fundamentos': 'Fundamentos',
  'nav.posicionamento': 'Posicionamento',
  'nav.nucleo': 'Núcleo da Marca',
  'nav.verbal': 'Universo Verbal',
  'nav.colors': 'Color Palette',
  'nav.typography': 'Typography',
  'nav.spacing-motion': 'Spacing & Motion',
  'nav.logo': 'Logo System',
  'nav.voice-tone': 'Voice & Tone',
  'nav.buttons': 'Buttons',
  'nav.cards': 'Cards',
  'nav.charts': 'Charts',
  'nav.forms': 'Forms',
  'nav.badges': 'Badges',
  'nav.feedback': 'Feedback',
  'nav.on-field': 'On-Field',
  'nav.off-field': 'Off-Field',
  'nav.performance': 'Performance Intelligence',
  'nav.sponsors': 'Sponsors',
  'nav.icons': 'Icons',
  'nav.arquitetura': 'Arquitetura',
  'nav.delivery': 'Delivery',
  'nav.ownership': 'Ownership',
  'nav.resources': 'Resources',

  // Overview (landing)
  'overview.eyebrow': '// BICOFINO DESIGN STUDIO',
  'overview.heading': 'Sistema de Design',
  'overview.intro': 'A referência viva de componentes, tokens e diretrizes da marca Bicofino. Modular, expansível, construído para evoluir.',

  // Brand System
  'fundamentos.eyebrow': '// 01 — FUNDAMENTOS',
  'fundamentos.heading': 'Fundamentos',
  'fundamentos.intro': 'Os princípios que estruturam todas as decisões visuais e de comunicação da marca.',

  'posicionamento.eyebrow': '// 01 — POSICIONAMENTO',
  'posicionamento.heading': 'Posicionamento',
  'posicionamento.intro': 'Como a Bicofino se posiciona no mercado e o que a diferencia no universo do futebol de alto desempenho.',

  'nucleo.eyebrow': '// 01 — NÚCLEO DA MARCA',
  'nucleo.heading': 'Núcleo da Marca',
  'nucleo.intro': 'Propósito, missão e os quatro pilares que definem a identidade Bicofino: Connect, Curate, Create, Consult.',

  'verbal.eyebrow': '// 01 — UNIVERSO VERBAL',
  'verbal.heading': 'Universo Verbal',
  'verbal.intro': 'A voz, o tom e o vocabulário da marca. Como falamos, para quem falamos e o que nunca dizemos.',

  // Visual System
  'colors.eyebrow': '// 02 — COLOR PALETTE',
  'colors.heading': 'Color Palette',
  'colors.intro': 'Um sistema fechado de cores. Cada token tem uma função — não existe cor decorativa na Bicofino.',

  'typography.eyebrow': '// 02 — TYPOGRAPHY',
  'typography.heading': 'Typography',
  'typography.intro': 'Inter para display e corpo. JetBrains Mono para metadados, eyebrows e código. Nada mais.',

  'spacing-motion.eyebrow': '// 02 — SPACING & MOTION',
  'spacing-motion.heading': 'Spacing & Motion',
  'spacing-motion.intro': 'Três valores de espaçamento. Três durações de animação. Sem valores intermediários.',

  'logo.eyebrow': '// 02 — LOGO SYSTEM',
  'logo.heading': 'Logo System',
  'logo.intro': 'O logotipo, o diamante e as regras de uso. Marca como sistema, não como ornamento.',

  'voice-tone.eyebrow': '// 02 — VOICE & TONE',
  'voice-tone.heading': 'Voice & Tone',
  'voice-tone.intro': 'Direta, técnica, confiante. A Bicofino fala com quem entende de futebol.',

  // Components
  'buttons.eyebrow': '// 03 — BUTTONS',
  'buttons.heading': 'Buttons',
  'buttons.intro': 'Todos os estados, tamanhos e variantes. Interação clara, feedback imediato.',

  'cards.eyebrow': '// 03 — CARDS',
  'cards.heading': 'Cards',
  'cards.intro': 'Containers de conteúdo com hierarquia clara. Stat cards, athlete cards, featured cards.',

  'charts.eyebrow': '// 03 — CHARTS',
  'charts.heading': 'Charts',
  'charts.intro': 'Visualizações animadas de dados de performance. SVG com entrada spring, responsivos.',

  'forms.eyebrow': '// 03 — FORMS',
  'forms.heading': 'Forms',
  'forms.intro': 'Inputs, selects, checkboxes. Estados de erro e validação visual incorporados.',

  'badges.eyebrow': '// 03 — BADGES',
  'badges.heading': 'Badges',
  'badges.intro': 'Indicadores de status, programa e categoria. Sistema de badges On-Field.',

  'feedback.eyebrow': '// 03 — FEEDBACK',
  'feedback.heading': 'Feedback',
  'feedback.intro': 'Toasts, alerts e indicadores de estado. Comunicação clara com o usuário.',

  // Verticais
  'on-field.eyebrow': '// 04 — ON-FIELD',
  'on-field.heading': 'On-Field',
  'on-field.intro': 'O universo visual do atleta. Identidade, performance e presença em campo.',

  'off-field.eyebrow': '// 04 — OFF-FIELD',
  'off-field.heading': 'Off-Field',
  'off-field.intro': 'A extensão da marca para fora do campo. Parceiros, clubes e operações comerciais.',

  // Assets
  'performance.eyebrow': '// 05 — PERFORMANCE INTELLIGENCE',
  'performance.heading': 'Performance Intelligence',
  'performance.intro': 'Dashboards e métricas que transformam dados em decisões de carreira.',

  'sponsors.eyebrow': '// 05 — SPONSORS',
  'sponsors.heading': 'Sponsors',
  'sponsors.intro': 'Parceiros e patrocinadores do ecossistema Bicofino.',

  'icons.eyebrow': '// 05 — ICONS',
  'icons.heading': 'Icons',
  'icons.intro': 'Lucide React, stroke 1.5, 20px. Sem ícones preenchidos.',

  // Operações
  'arquitetura.eyebrow': '// 06 — ARQUITETURA',
  'arquitetura.heading': 'Arquitetura',
  'arquitetura.intro': 'Como o ecossistema Bicofino está estruturado: produtos, times e fluxos.',

  'delivery.eyebrow': '// 06 — DELIVERY',
  'delivery.heading': 'Delivery',
  'delivery.intro': 'Processos de entrega, versionamento e controle de qualidade.',

  // Governança
  'ownership.eyebrow': '// 07 — OWNERSHIP',
  'ownership.heading': 'Ownership',
  'ownership.intro': 'Quem é responsável por quê no design system Bicofino.',

  'resources.eyebrow': '// 07 — RESOURCES',
  'resources.heading': 'Resources',
  'resources.intro': 'Links, ferramentas e documentação de suporte.',

  // Visual System — Colors
  'color.black.role': 'Primária',
  'color.black.desc': 'Texto principal, fundos escuros, ícones',
  'color.steel.role': 'Secundária',
  'color.steel.desc': 'Texto de suporte, metadados, bordas médias',
  'color.aluminium.role': 'Terciária',
  'color.aluminium.desc': 'Fundos de seção, separadores suaves',
  'color.platinum.role': 'Destaque frio',
  'color.platinum.desc': 'Highlights, gradientes de foco',
  'color.bg.role': 'Background',
  'color.bg.desc': 'Fundo da página e superfícies principais',
  'color.white.role': 'Branco puro',
  'color.white.desc': 'Superfícies de cards e overlays',
  'color.powerblack.role': 'Power Black',
  'color.powerblack.desc': 'Seções de alto contraste, covers escuros',
  'color.crema.role': 'Crema',
  'color.caffe.role': 'Caffè',
  'color.champagne.role': 'Champagne',
  'color.cacao.role': 'Cacao',
  'colors.basics.title': 'Palette Base',
  'colors.specials.title': 'Cores Especiais',
  'colors.highlights.label': '// 02.2.3',
  'colors.highlights.title': 'Destaques — Atletas e Clubes',
  'colors.tokens.title': 'Token Reference',
  'token.black.role': 'Texto primário',
  'token.powerblack.role': 'Fundo de alto contraste',
  'token.bg.role': 'Background azul',
  'token.white.role': 'Superfície branca',
  'token.steel.role': 'Texto secundário',
  'token.aluminium.role': 'Separadores e fundos suaves',
  'token.platinum.role': 'Destaque frio',
  'token.crema.role': 'Acento quente claro',
  'token.caffe.role': 'Acento quente escuro',
  'token.cacao.role': 'Marrom médio',
  'token.torino.role': 'Torino FC',
  'token.como.role': 'Como FC',
  'token.spfc.role': 'São Paulo FC',
  'table.col.token': 'Token',
  'table.col.value': 'Valor',
  'table.col.name': 'Nome',
  'table.col.role': 'Função',

  // Visual System — Typography
  'font.inter.subtitle': 'Display, títulos e corpo de texto',
  'font.inter.family': 'Inter',
  'font.inter.weights': '400, 500, 600, 700',
  'font.inter.coverage': 'Latim estendido',
  'font.inter.usage': 'Todos os textos display, headings e corpo',
  'font.inter.license': 'SIL Open Font License',
  'font.mono.subtitle': 'Metadados, eyebrows, código e labels',
  'font.mono.family': 'JetBrains Mono',
  'font.mono.weights': '400, 600',
  'font.mono.coverage': 'Latim',
  'font.mono.usage': 'Eyebrows, labels técnicos, fragmentos de código',
  'font.mono.license': 'SIL Open Font License',
  'font.meta.family': 'Família',
  'font.meta.weights': 'Pesos',
  'font.meta.coverage': 'Cobertura',
  'font.meta.usage': 'Uso',
  'font.meta.license': 'Licença',
  'typescale.eyebrow.specimen': 'BICOFINO / 2026',
  'typescale.eyebrow.meta': '11px / 1.4 · 0.12em · 600 uppercase',

  // Visual System — Spacing & Motion
  'spacing.section.title': 'Tokens de Espaçamento',
  'spacing.col.token': 'Token',
  'spacing.col.px': 'px',
  'spacing.col.rem': 'rem',
  'spacing.col.usage': 'Uso',
  'spacing.col.visual': 'Visual',
  'motion.section.title': 'Duração de Movimento',
  'radius.section.title': 'Border Radius',
  'radius.label.sm': 'sm · 4px',
  'radius.label.md': 'md · 8px',
  'radius.label.lg': 'lg · 16px',
  'sp1.uso': 'Micro gap interno',
  'sp2.uso': 'Gap entre ícone e label',
  'sp3.uso': 'Padding compacto',
  'sp4.uso': 'Padding de botão / gap padrão',
  'sp5.uso': 'Padding interno de card',
  'sp6.uso': 'Padding de seção compacta',
  'sp7.uso': 'Padding de seção standard',
  'sp8.uso': 'Espaço entre blocos',
  'sp9.uso': 'Margem de página top/bottom',

  // Visual System — Logo System
  'brand.logo.light': '// fundo claro',
  'brand.logo.dark': '// fundo escuro',
  'brand.logo.crema': '// fundo crema',
  'brand.logo.aluminium': '// fundo alumínio',
  'brand.logo.sizes.label': '// tamanhos recomendados',
  'brand.logo.sizes.display': 'display',
  'brand.logo.sizes.padrao': 'padrão',
  'brand.logo.sizes.compacto': 'compacto',
  'brand.logo.sizes.minimo': 'mínimo',
  'brand.logo.sizes.evitar': 'evitar',
  'brand.logo.minrec': '// tamanho mínimo recomendado: 48px',
  'brand.logo.rules.label': '// regras de uso',
  'brand.logo.rule1': 'Não distorcer ou alterar proporções do logotipo.',
  'brand.logo.rule2': 'Não aplicar sombras, gradientes ou efeitos visuais.',
  'brand.logo.rule3': 'Manter área de respiro mínima equivalente à altura da letra "B".',
  'brand.logo.rule4': 'Usar apenas nas versões escura e clara aprovadas.',
  'brand.diamond.label': '// diamante bicofino',
  'brand.diamond.lead': 'O diamante é o símbolo de acesso e excelência da Bicofino.',
  'brand.diamond.lead2': 'Usado isolado como ícone de marca ou em combinação com o logotipo em contextos de alto contraste.',
  'brand.diamond.light': '// fundo claro',
  'brand.diamond.dark': '// fundo escuro',
  'brand.diamond.crema': '// fundo crema',
  'brand.diamond.aluminium': '// fundo alumínio',
  'brand.diamond.sizes.label': '// tamanhos recomendados',
  'brand.diamond.minrec': '// tamanho mínimo recomendado: 20px',

  // Visual System — Voice & Tone
  'voice.direct.label': 'Direta',
  'voice.direct.desc': 'Frases curtas. Sem rodeios. O Bicofino não explica o que já é óbvio para quem entende de futebol.',
  'voice.confident.label': 'Confiante',
  'voice.confident.desc': 'Nunca tentativa, nunca hedging. Afirmações, não sugestões.',
  'voice.editorial.label': 'Editorial',
  'voice.editorial.desc': 'A escrita tem ritmo. Escolha de palavras importa. Qualidade que se sente antes de se ler.',
  'voice.nocliches.label': 'Sem clichês',
  'voice.nocliches.desc': 'Sem "apaixonado por", "dedicado a", "comprometido com". O Bicofino prova, não proclama.',
  'voice.bilingual.label': 'Bilíngue',
  'voice.bilingual.desc': 'Português e inglês convivem naturalmente. Nunca tradução literal — sempre adaptação cultural.',

  // Common
  'common.coming-soon': 'Em desenvolvimento',
  'common.coming-soon-detail': 'Esta seção está sendo construída. Volte em breve.',
  'common.wip': 'Work in Progress',

  // Section 03 — Components Gallery
  comp_eyebrow: 'Seção 03',
  comp_heading: 'Componentes',
  comp_intro: 'Todos os componentes do sistema — cada peça construída sobre os mesmos tokens.',

  comp_buttons_eyebrow: 'Buttons',
  comp_buttons_heading: 'Botões',
  comp_buttons_desc: 'Quatro variantes, três tamanhos, estados completos.',
  comp_buttons_primary: 'Primário',
  comp_buttons_secondary: 'Secundário',
  comp_buttons_ghost: 'Ghost',
  comp_buttons_destructive: 'Destrutivo',
  comp_buttons_loading: 'Carregando…',
  comp_buttons_disabled: 'Desabilitado',

  comp_cards_eyebrow: 'Cards',
  comp_cards_heading: 'Cards',
  comp_cards_desc: 'Superfície base para agrupar conteúdo relacionado.',
  comp_cards_default: 'Card padrão',
  comp_cards_metric: 'Card de métrica',
  comp_cards_athlete: 'Card de atleta',

  comp_charts_eyebrow: 'Charts',
  comp_charts_heading: 'Gráficos',
  comp_charts_desc: 'Visualizações de dados com tokens de cor dedicados.',
  comp_charts_line: 'Linha',
  comp_charts_bar: 'Barras',
  comp_charts_donut: 'Donut',

  comp_forms_eyebrow: 'Forms',
  comp_forms_heading: 'Formulários',
  comp_forms_desc: 'Inputs, selects e controles com estados de validação.',
  comp_forms_label_name: 'Nome',
  comp_forms_placeholder_name: 'Ex.: João Silva',
  comp_forms_label_sport: 'Modalidade',
  comp_forms_label_active: 'Atleta ativo',
  comp_forms_label_notify: 'Receber notificações',

  comp_badges_eyebrow: 'Badges',
  comp_badges_heading: 'Badges',
  comp_badges_desc: 'Status, tags e labels — todas as variantes de cor.',
  comp_badges_active: 'Ativo',
  comp_badges_inactive: 'Inativo',
  comp_badges_pending: 'Pendente',
  comp_badges_new: 'Novo',
  comp_badges_featured: 'Destaque',
  comp_badges_archived: 'Arquivado',

  comp_feedback_eyebrow: 'Feedback',
  comp_feedback_heading: 'Feedback',
  comp_feedback_desc: 'Alertas, toasts, estados vazios e skeletons.',
  comp_feedback_alert_success: 'Operação concluída com sucesso.',
  comp_feedback_alert_warning: 'Atenção: verifique os dados antes de continuar.',
  comp_feedback_alert_error: 'Erro ao processar a requisição.',
  comp_feedback_empty_title: 'Nenhum resultado',
  comp_feedback_empty_desc: 'Tente ajustar os filtros ou adicionar novos dados.',

  // Section 04 — Verticais
  vert_eyebrow: 'Seção 04',
  vert_heading: 'Verticais',
  vert_intro: 'O Bicofino Group opera em duas frentes editoriais. Cada uma tem expressão visual própria, dentro do sistema.',

  vert_onfield_eyebrow: 'On-Field',
  vert_onfield_heading: 'On Field — Athlete Image System',
  vert_onfield_subhead: 'Imagem como presença. Dados como prova.',
  vert_onfield_desc: 'O sistema On Field trata o atleta como o principal ativo visual. As imagens não são colocadas dentro de cards genéricos — elas criam hierarquia, tensão e presença. Os dados sustentam a narrativa com precisão.',
  vert_onfield_tone: 'Futebol. Competição. Resultados. Comunicação de alta intensidade — destaques visuais, cores de programa, urgência editorial.',
  vert_onfield_serves: 'Quem serve',
  vert_onfield_serves_desc: 'Atletas do portfólio Bicofino — principalmente jovens talentos do futebol com potencial de carreira internacional.',
  vert_onfield_delivers: 'O que On Field entrega',
  vert_onfield_d1: 'Agenciamento e representação de atletas',
  vert_onfield_d2: 'Desenvolvimento físico, tático, mental e cognitivo',
  vert_onfield_d3: 'Monitoramento de performance e saúde',
  vert_onfield_d4: 'Gestão de contratos com clubes',
  vert_onfield_d5: 'Posicionamento para mercados internacionais',
  vert_onfield_d6: 'Media kit e perfil de atleta para scouts e clubes',
  vert_onfield_catalog: 'Estrutura de Assets On Field',
  vert_onfield_cat_portraits: 'Retratos de Atletas',
  vert_onfield_cat_campaigns: 'Imagens de Campanha',
  vert_onfield_cat_brand: 'Marca Pessoal',
  vert_onfield_cat_badges: 'Badges Bicofino',
  vert_onfield_cat_clubs: 'Escudos de Clubes',
  vert_onfield_cat_sponsors: 'Logos de Patrocinadores',
  vert_onfield_cat_passports: 'Passaportes / Nações',
  vert_onfield_cat_icons: 'Ícones de Performance',

  vert_offfield_eyebrow: 'Off-Field',
  vert_offfield_heading: 'Off Field — Beyond the Pitch',
  vert_offfield_subhead: 'Tudo que existe fora do campo.',
  vert_offfield_desc: 'Off Field reúne todos os serviços que fazem o atleta, a marca ou a empresa crescer além da performance esportiva. É aqui que o Bicofino também serve marcas e empresas — com ou sem conexão direta com atletas.',
  vert_offfield_tone: 'Lifestyle. Cultura. Estilo de vida premium. Comunicação editorial sofisticada — quiet luxury, espaço em branco, tipografia, restraint.',
  vert_offfield_serves: 'Quem serve',
  vert_offfield_serves_desc: 'Atletas do portfólio (extra-campo), marcas premium e executivos que buscam curadoria criativa e estratégica de alto nível.',
  vert_offfield_delivers: 'O que Off Field entrega',
  vert_offfield_d1: 'Branding e identidade visual',
  vert_offfield_d2: 'Advertising e produção de conteúdo',
  vert_offfield_d3: 'Design, motion e direção de arte',
  vert_offfield_d4: 'PR e personal branding executivo',
  vert_offfield_d5: 'Consultoria jurídica e planejamento tributário',
  vert_offfield_d6: 'Family office e planejamento financeiro',
  vert_offfield_d7: 'Conexão entre marcas, atletas e personalidades',
  vert_offfield_diff: 'O diferencial Off Field',
  vert_offfield_diff_desc: 'O Bicofino conecta marcas e empresas a atletas, celebridades e personalidades fora do alcance da maioria. Esse acesso foi construído com anos de relacionamentos éticos e presença consistente nos mercados certos.',

  // Section 05 — Assets
  assets_eyebrow: 'Seção 05',
  assets_heading: 'Assets',
  assets_intro: 'Componentes vivos, sponsors e sistema de ícones.',

  assets_perf_eyebrow: 'Performance Intelligence',
  assets_perf_heading: 'Performance Intelligence',
  assets_perf_lead: 'Visualização viva do sistema Bicofino OS. Cada número representa eficiência real — tempo recuperado, output amplificado, custo eliminado.',
  assets_perf_metrics_title: 'Métricas do Sistema',
  assets_perf_chart_title: 'Bicofino OS vs. Tradicional',
  assets_perf_chart_lead: 'A vantagem composta do Bicofino OS. A linha tradicional cresce linearmente — o sistema Bicofino cresce exponencialmente.',
  assets_perf_c1_label: 'Tempo Salvo / Semana',
  assets_perf_c1_desc: 'Por consultor',
  assets_perf_c2_label: 'Multiplicador de Output',
  assets_perf_c2_desc: 'vs. fluxo tradicional',
  assets_perf_c3_label: 'Redução de Custo',
  assets_perf_c3_desc: 'Overhead operacional',
  assets_perf_c4_label: 'Ganho de Eficiência',
  assets_perf_c4_desc: 'Ano a ano',
  assets_perf_c5_label: 'Agentes Ativos',
  assets_perf_c5_desc: 'Em paralelo',
  assets_perf_c6_label: 'Tempo de Resposta',
  assets_perf_c6_desc: 'Latência média do sistema',

  assets_sponsors_eyebrow: 'Sponsors',
  assets_sponsors_heading: 'Sponsors',
  assets_sponsors_lead: 'Marcas globais e empresas de referência com as quais o Bicofino mantém relações próximas — construídas com acesso, confiança e contexto estratégico.',

  assets_icons_eyebrow: 'Icons',
  assets_icons_heading: 'Icons',
  assets_icons_lead: 'Sistema de ícones baseado em Lucide. Traço consistente, peso único, escala previsível. Clique em qualquer ícone para copiar o snippet React.',
  assets_icons_copied: 'Copiado!',
  assets_icons_copy_hint: 'Clique para copiar',

  // Section 06 — Operações
  ops_eyebrow: 'Seção 06',
  ops_heading: 'Operações',
  ops_lead: 'O Bicofino Group organiza suas operações em duas grandes vertentes e um projeto confidencial.',

  ops_arch_label: '// 06.1',
  ops_arch_title: 'Arquitetura de Marca',

  ops_onfield_title: 'ON FIELD',
  ops_onfield_subtitle: 'Tudo relativo ao atleta e sua performance em campo',
  ops_onfield_desc: 'On Field reúne todos os serviços e especialistas dedicados ao atleta como performer. Médicos, especialistas em performance física, nutricionistas, psicólogos esportivos, coaches táticos, tecnologia de análise de dados — tudo que potencializa o atleta dentro do campo e garante que ele chegue ao mais alto nível de competição.',
  ops_onfield_delivers: 'O que On Field entrega:',
  ops_onfield_d1: 'Agenciamento e representação de atletas',
  ops_onfield_d2: 'Desenvolvimento físico, tático, mental e cognitivo',
  ops_onfield_d3: 'Monitoramento de performance e saúde',
  ops_onfield_d4: 'Gestão de contratos com clubes',
  ops_onfield_d5: 'Posicionamento para mercados internacionais',
  ops_onfield_d6: 'Media kit e perfil de atleta para scouts e clubes',
  ops_onfield_serves: 'Quem serve:',
  ops_onfield_serves_desc: 'Atletas do portfólio Bicofino — principalmente jovens talentos do futebol com potencial de carreira internacional.',

  ops_offfield_title: 'OFF FIELD',
  ops_offfield_subtitle: 'Tudo que existe fora do campo',
  ops_offfield_desc: 'Off Field reúne todos os serviços que fazem o atleta, a marca ou a empresa crescer além da performance esportiva. É aqui que o Bicofino também serve marcas e empresas — com ou sem conexão direta com atletas.',
  ops_offfield_delivers: 'O que Off Field entrega:',
  ops_offfield_d1: 'Branding e identidade visual (atletas, marcas, empresas)',
  ops_offfield_d2: 'Advertising e produção de conteúdo',
  ops_offfield_d3: 'Design, motion e direção de arte',
  ops_offfield_d4: 'PR e personal branding executivo',
  ops_offfield_d5: 'Consultoria jurídica e planejamento tributário',
  ops_offfield_d6: 'Family office e planejamento financeiro (Wealth)',
  ops_offfield_d7: 'Conexão entre marcas, empresas, atletas e personalidades',
  ops_offfield_serves: 'Quem serve:',
  ops_offfield_serves_desc: 'Atletas do portfólio (extra-campo), marcas premium e executivos que buscam curadoria criativa e estratégica de alto nível.',
  ops_offfield_diff: 'O diferencial Off Field:',
  ops_offfield_diff_desc: 'O Bicofino conecta marcas e empresas a atletas, celebridades e personalidades que estão fora do alcance da grande maioria. Esse acesso foi construído com anos de relacionamentos éticos, negociações limpas e presença consistente nos mercados certos.',

  ops_club_title: 'CLUB',
  ops_club_subtitle: 'Território da Raposa — confidencial',
  ops_club_desc: 'O Club é o projeto mais íntimo e seletivo do Bicofino. Seu perfil, critérios e membros são mantidos em total discrição.',
  ops_club_confidential: 'Detalhes não documentados publicamente neste Brand System.',

  ops_visual_label: '// Arquitetura visual das vertentes',
  ops_visual_desc: 'On Field e Off Field compartilham o mesmo DNA visual — Inter, diamond ✦, paleta core, hierarquia de leitura. O que diferencia uma da outra é o universo de imagem:',
  ops_visual_onfield: 'sempre imagens dos atletas em campo, em treino, em competição',
  ops_visual_offfield: 'imagens dos atletas em relação a marcas, campanhas, empresas e design — além de projetos que não envolvem atletas',

  ops_delivery_label: '// 06.2',
  ops_delivery_title: 'Padrões de Entrega',
  ops_delivery_desc: 'Todo output do Bicofino passa pelo filtro dos 6 Princípios de Operação antes de ser entregue:',
  ops_p1_title: 'Obsessão genuína por detalhes',
  ops_p1_desc: 'Existe algo aqui que pode ser mais preciso?',
  ops_p2_title: 'Beleza e inteligência no design',
  ops_p2_desc: 'Esta entrega é ao mesmo tempo bonita e estratégica?',
  ops_p3_title: 'Entregar mais que o esperado',
  ops_p3_desc: 'O cliente vai perceber que recebeu além do briefing?',
  ops_p4_title: 'Simples, nunca simplista',
  ops_p4_desc: 'Existe algo que pode ser cortado sem perder substância?',
  ops_p5_title: 'Contundência com elegância',
  ops_p5_desc: 'A mensagem é clara e está entregue com o tom correto?',
  ops_p6_title: 'Tecnologia a serviço da criatividade',
  ops_p6_desc: 'IA e dados foram usados como amplificadores?',

  ops_tools_label: '// Ferramentas de operação',
  ops_tools_col_role: 'FUNÇÃO',
  ops_tools_col_tool: 'FERRAMENTA',
  ops_tool_memory_role: 'Memória',
  ops_tool_memory_name: 'Google Drive + Supabase',
  ops_tool_org_role: 'Organização',
  ops_tool_org_name: 'Dashboard próprio em desenvolvimento',
  ops_tool_orch_role: 'Orquestração',
  ops_tool_orch_name: 'Claude no terminal · Agentes de IA em desenvolvimento',
  ops_tool_intel_role: 'Inteligência / Estratégia / Copy',
  ops_tool_intel_name: 'Claude (primário) · ChatGPT · Gemini',
  ops_tool_design_role: 'Design / Interface',
  ops_tool_design_name: 'Photoshop · Illustrator · Claude Code (React, Tailwind, shadcn)',
  ops_tool_vi_role: 'Identidade Visual',
  ops_tool_vi_name: 'Pacote Adobe',
  ops_tool_video_role: 'Edição de Vídeo',
  ops_tool_video_name: 'Adobe Premiere',
  ops_tool_motion_role: 'Motion',
  ops_tool_motion_name: 'Claude Code (componentes) · After Effects',
  ops_tool_imggen_role: 'Geração de Imagens',
  ops_tool_imggen_name: 'Magnific · ChatGPT',
  ops_tool_vidgen_role: 'Geração de Vídeo',
  ops_tool_vidgen_name: 'Magnific · Google VEO',

  ops_flow_label: '// Fluxo de entrega Off Field — Studio',
  ops_flow_s1: 'Briefing ou entrada de demanda (sexta-feira preferencial)',
  ops_flow_s2: 'Produção — 2 dias úteis para projetos recorrentes',
  ops_flow_s3: 'Revisão interna — 1 dia útil',
  ops_flow_s4: 'Entrega ao cliente',
  ops_flow_s5: 'Rodada de ajuste inclusa no escopo',
  ops_flow_s6: 'Aprovação e arquivamento',

  ops_commercial_label: '// Política comercial',
  ops_policy1: 'Sem desconto sobre valor. Ajuste via redução de escopo, nunca de qualidade.',
  ops_policy2: 'Agenda limitada. Lista de espera quando necessário.',
  ops_policy3: 'Honorários do Studio, budget de mídia e custos de produção são itens separados e independentes.',
  ops_policy4: 'Toda proposta no formato dossiê — nunca lista de preços ou pacotes.',

  ops_brand_line1: 'Brand System — Bicofino Group SA',
  ops_brand_line2: 'Elaborado e mantido pelo Studio Bicofino',
  ops_brand_line3: 'Woney Malian / Fabio Brancatelli',
  ops_brand_version: 'v1.0 · São Paulo, BR · Maio 2026',
  ops_brand_tagline: 'Unlike Any Other.',

  // Section 07 — Governança
  gov_eyebrow: 'Seção 07',
  gov_heading: 'Governança',

  gov_ownership_eyebrow: 'Ownership',
  gov_ownership_heading: 'Versão & Owners',
  gov_ownership_lead: 'Cada camada do sistema tem um responsável claro. Mudanças nos Foundations requerem revisão dos owners. Components e Patterns podem ser propostos por qualquer membro da equipe.',
  gov_col_layer: 'LAYER',
  gov_col_owner: 'OWNER',
  gov_col_scope: 'SCOPE',
  gov_foundations_scope: 'Tokens, tipografia, paleta, grid',
  gov_brand_scope: 'Wordmark, voz, verticais',
  gov_components_scope: 'UI patterns, código React/CSS',
  gov_governance_scope: 'Versão, changelogs, arquivos',

  gov_resources_eyebrow: 'Resources',
  gov_resources_heading: 'Resources',
  gov_col_file: 'ARQUIVO',
  gov_col_purpose: 'PROPÓSITO',
  gov_r1_purpose: 'CSS custom properties — fonte de verdade para tokens',
  gov_r2_purpose: 'Instruções para agentes de IA — regras de execução',
  gov_r3_purpose: 'Manual de Identidade Visual — fonte de verdade editorial',
  gov_r4_purpose: 'Estado global do projeto e pendências',
  gov_r5_purpose: 'Configuração de navegação — única fonte de verdade do nav',
  gov_r6_purpose: 'Conteúdo trilíngue — BR / EN / IT',
  gov_r7_purpose: 'Provedores globais — tema, idioma',
  gov_r8_purpose: 'Rastreamento de progresso do projeto',
  skip_to_content: 'Ir para o conteúdo',
} as const

export type ContentKey = keyof typeof br
