export const en = {
  // Site
  'site.title': 'Bicofino Design Studio',
  'site.description': 'Visual and brand system — complete reference of components and guidelines.',

  // UI controls
  'ui.theme.toggle': 'Toggle theme',
  'ui.lang.label': 'Language',
  'ui.menu.open': 'Open menu',
  'ui.menu.close': 'Close menu',

  // Language labels
  'lang.br': 'Português',
  'lang.en': 'English',
  'lang.it': 'Italiano',

  // Nav groups
  'nav.brand-system': 'Brand System',
  'nav.visual-system': 'Visual System',
  'nav.components': 'Components',
  'nav.verticais': 'Verticals',
  'nav.assets': 'Assets',
  'nav.operacoes': 'Operations',
  'nav.governanca': 'Governance',

  // Nav items
  'nav.fundamentos': 'Foundations',
  'nav.posicionamento': 'Positioning',
  'nav.nucleo': 'Brand Core',
  'nav.verbal': 'Verbal Universe',
  'nav.colors': 'Color Palette',
  'nav.typography': 'Typography',
  'nav.spacing-motion': 'Spacing & Motion',
  'nav.logo': 'Logo System',
  'nav.voice-tone': 'Voice & Tone',
  'nav.buttons': 'Buttons',
  'nav.cards': 'Cards',
  'nav.charts': 'Charts',
  'nav.forms': 'Forms',
  'nav.badges': 'Badges',
  'nav.feedback': 'Feedback',
  'nav.on-field': 'On-Field',
  'nav.off-field': 'Off-Field',
  'nav.performance': 'Performance Intelligence',
  'nav.sponsors': 'Sponsors',
  'nav.icons': 'Icons',
  'nav.arquitetura': 'Architecture',
  'nav.delivery': 'Delivery',
  'nav.ownership': 'Ownership',
  'nav.resources': 'Resources',

  // Overview
  'overview.eyebrow': '// BICOFINO DESIGN STUDIO',
  'overview.heading': 'Design System',
  'overview.intro': 'The living reference of components, tokens and brand guidelines of Bicofino. Modular, extensible, built to evolve.',

  // Brand System
  'fundamentos.eyebrow': '// 01 — FOUNDATIONS',
  'fundamentos.heading': 'Foundations',
  'fundamentos.intro': 'The principles that structure all visual and communication decisions of the brand.',

  'posicionamento.eyebrow': '// 01 — POSITIONING',
  'posicionamento.heading': 'Positioning',
  'posicionamento.intro': 'How Bicofino positions itself in the market and what sets it apart in the high-performance football universe.',

  'nucleo.eyebrow': '// 01 — BRAND CORE',
  'nucleo.heading': 'Brand Core',
  'nucleo.intro': 'Purpose, mission and the four pillars that define Bicofino identity: Connect, Curate, Create, Consult.',

  'verbal.eyebrow': '// 01 — VERBAL UNIVERSE',
  'verbal.heading': 'Verbal Universe',
  'verbal.intro': 'The voice, tone and vocabulary of the brand. How we speak, to whom we speak and what we never say.',

  // Visual System
  'colors.eyebrow': '// 02 — COLOR PALETTE',
  'colors.heading': 'Color Palette',
  'colors.intro': 'A closed colour system. Every token has a function — there are no decorative colours in Bicofino.',

  'typography.eyebrow': '// 02 — TYPOGRAPHY',
  'typography.heading': 'Typography',
  'typography.intro': 'Inter for display and body. JetBrains Mono for metadata, eyebrows and code. Nothing else.',

  'spacing-motion.eyebrow': '// 02 — SPACING & MOTION',
  'spacing-motion.heading': 'Spacing & Motion',
  'spacing-motion.intro': 'Three spacing values. Three animation durations. No intermediate values.',

  'logo.eyebrow': '// 02 — LOGO SYSTEM',
  'logo.heading': 'Logo System',
  'logo.intro': 'The logotype, the diamond and the rules of use. Brand as system, not ornament.',

  'voice-tone.eyebrow': '// 02 — VOICE & TONE',
  'voice-tone.heading': 'Voice & Tone',
  'voice-tone.intro': 'Direct, technical, confident. Bicofino speaks to those who understand football.',

  // Components
  'buttons.eyebrow': '// 03 — BUTTONS',
  'buttons.heading': 'Buttons',
  'buttons.intro': 'All states, sizes and variants. Clear interaction, immediate feedback.',

  'cards.eyebrow': '// 03 — CARDS',
  'cards.heading': 'Cards',
  'cards.intro': 'Content containers with clear hierarchy. Stat cards, athlete cards, featured cards.',

  'charts.eyebrow': '// 03 — CHARTS',
  'charts.heading': 'Charts',
  'charts.intro': 'Animated performance data visualisations. SVG with spring entry, responsive.',

  'forms.eyebrow': '// 03 — FORMS',
  'forms.heading': 'Forms',
  'forms.intro': 'Inputs, selects, checkboxes. Error states and visual validation built in.',

  'badges.eyebrow': '// 03 — BADGES',
  'badges.heading': 'Badges',
  'badges.intro': 'Status, programme and category indicators. On-Field badge system.',

  'feedback.eyebrow': '// 03 — FEEDBACK',
  'feedback.heading': 'Feedback',
  'feedback.intro': 'Toasts, alerts and state indicators. Clear communication with the user.',

  // Verticals
  'on-field.eyebrow': '// 04 — ON-FIELD',
  'on-field.heading': 'On-Field',
  'on-field.intro': "The athlete's visual universe. Identity, performance and presence on the pitch.",

  'off-field.eyebrow': '// 04 — OFF-FIELD',
  'off-field.heading': 'Off-Field',
  'off-field.intro': 'The brand extension beyond the pitch. Partners, clubs and commercial operations.',

  // Assets
  'performance.eyebrow': '// 05 — PERFORMANCE INTELLIGENCE',
  'performance.heading': 'Performance Intelligence',
  'performance.intro': 'Dashboards and metrics that turn data into career decisions.',

  'sponsors.eyebrow': '// 05 — SPONSORS',
  'sponsors.heading': 'Sponsors',
  'sponsors.intro': 'Partners and sponsors of the Bicofino ecosystem.',

  'icons.eyebrow': '// 05 — ICONS',
  'icons.heading': 'Icons',
  'icons.intro': 'Lucide React, stroke 1.5, 20px. No filled icons.',

  // Operations
  'arquitetura.eyebrow': '// 06 — ARCHITECTURE',
  'arquitetura.heading': 'Architecture',
  'arquitetura.intro': 'How the Bicofino ecosystem is structured: products, teams and flows.',

  'delivery.eyebrow': '// 06 — DELIVERY',
  'delivery.heading': 'Delivery',
  'delivery.intro': 'Delivery processes, versioning and quality control.',

  // Governance
  'ownership.eyebrow': '// 07 — OWNERSHIP',
  'ownership.heading': 'Ownership',
  'ownership.intro': 'Who is responsible for what in the Bicofino design system.',

  'resources.eyebrow': '// 07 — RESOURCES',
  'resources.heading': 'Resources',
  'resources.intro': 'Links, tools and supporting documentation.',

  // Visual System — Colors
  'color.black.role': 'Primary',
  'color.black.desc': 'Main text, dark backgrounds, icons',
  'color.steel.role': 'Secondary',
  'color.steel.desc': 'Supporting text, metadata, medium borders',
  'color.aluminium.role': 'Tertiary',
  'color.aluminium.desc': 'Section backgrounds, soft dividers',
  'color.platinum.role': 'Cold highlight',
  'color.platinum.desc': 'Highlights, focus gradients',
  'color.bg.role': 'Background',
  'color.bg.desc': 'Page background and main surfaces',
  'color.white.role': 'Pure white',
  'color.white.desc': 'Card surfaces and overlays',
  'color.powerblack.role': 'Power Black',
  'color.powerblack.desc': 'High-contrast sections, dark covers',
  'color.crema.role': 'Crema',
  'color.caffe.role': 'Caffè',
  'color.champagne.role': 'Champagne',
  'color.cacao.role': 'Cacao',
  'colors.basics.title': 'Base Palette',
  'colors.specials.title': 'Special Colors',
  'colors.highlights.label': '// 02.2.3',
  'colors.highlights.title': 'Highlights — Athletes & Clubs',
  'colors.tokens.title': 'Token Reference',
  'token.black.role': 'Primary text',
  'token.powerblack.role': 'High-contrast background',
  'token.bg.role': 'Blue background',
  'token.white.role': 'White surface',
  'token.steel.role': 'Secondary text',
  'token.aluminium.role': 'Dividers and soft backgrounds',
  'token.platinum.role': 'Cold highlight',
  'token.crema.role': 'Light warm accent',
  'token.caffe.role': 'Dark warm accent',
  'token.cacao.role': 'Medium brown',
  'token.torino.role': 'Torino FC',
  'token.como.role': 'Como FC',
  'token.spfc.role': 'São Paulo FC',
  'table.col.token': 'Token',
  'table.col.value': 'Value',
  'table.col.name': 'Name',
  'table.col.role': 'Role',

  // Visual System — Typography
  'font.inter.subtitle': 'Display, headings and body text',
  'font.inter.family': 'Inter',
  'font.inter.weights': '400, 500, 600, 700',
  'font.inter.coverage': 'Extended Latin',
  'font.inter.usage': 'All display text, headings and body',
  'font.inter.license': 'SIL Open Font License',
  'font.mono.subtitle': 'Metadata, eyebrows, code and labels',
  'font.mono.family': 'JetBrains Mono',
  'font.mono.weights': '400, 600',
  'font.mono.coverage': 'Latin',
  'font.mono.usage': 'Eyebrows, technical labels, code snippets',
  'font.mono.license': 'SIL Open Font License',
  'font.meta.family': 'Family',
  'font.meta.weights': 'Weights',
  'font.meta.coverage': 'Coverage',
  'font.meta.usage': 'Usage',
  'font.meta.license': 'License',
  'typescale.eyebrow.specimen': 'BICOFINO / 2026',
  'typescale.eyebrow.meta': '11px / 1.4 · 0.12em · 600 uppercase',

  // Visual System — Spacing & Motion
  'spacing.section.title': 'Spacing Tokens',
  'spacing.col.token': 'Token',
  'spacing.col.px': 'px',
  'spacing.col.rem': 'rem',
  'spacing.col.usage': 'Usage',
  'spacing.col.visual': 'Visual',
  'motion.section.title': 'Motion Duration',
  'radius.section.title': 'Border Radius',
  'radius.label.sm': 'sm · 4px',
  'radius.label.md': 'md · 8px',
  'radius.label.lg': 'lg · 16px',
  'sp1.uso': 'Micro internal gap',
  'sp2.uso': 'Icon-to-label gap',
  'sp3.uso': 'Compact padding',
  'sp4.uso': 'Button padding / standard gap',
  'sp5.uso': 'Card internal padding',
  'sp6.uso': 'Compact section padding',
  'sp7.uso': 'Standard section padding',
  'sp8.uso': 'Block spacing',
  'sp9.uso': 'Page top/bottom margin',

  // Visual System — Logo System
  'brand.logo.light': '// light background',
  'brand.logo.dark': '// dark background',
  'brand.logo.crema': '// crema background',
  'brand.logo.aluminium': '// aluminium background',
  'brand.logo.sizes.label': '// recommended sizes',
  'brand.logo.sizes.display': 'display',
  'brand.logo.sizes.padrao': 'standard',
  'brand.logo.sizes.compacto': 'compact',
  'brand.logo.sizes.minimo': 'minimum',
  'brand.logo.sizes.evitar': 'avoid',
  'brand.logo.minrec': '// minimum recommended size: 48px',
  'brand.logo.rules.label': '// usage rules',
  'brand.logo.rule1': 'Do not distort or alter logo proportions.',
  'brand.logo.rule2': 'Do not apply shadows, gradients or visual effects.',
  'brand.logo.rule3': 'Maintain minimum clear space equal to the height of the letter "B".',
  'brand.logo.rule4': 'Use only in approved dark and light versions.',
  'brand.diamond.label': '// bicofino diamond',
  'brand.diamond.lead': 'The diamond is the Bicofino symbol of access and excellence.',
  'brand.diamond.lead2': 'Used standalone as a brand icon or in combination with the logotype in high-contrast contexts.',
  'brand.diamond.light': '// light background',
  'brand.diamond.dark': '// dark background',
  'brand.diamond.crema': '// crema background',
  'brand.diamond.aluminium': '// aluminium background',
  'brand.diamond.sizes.label': '// recommended sizes',
  'brand.diamond.minrec': '// minimum recommended size: 20px',

  // Visual System — Voice & Tone
  'voice.direct.label': 'Direct',
  'voice.direct.desc': 'Short sentences. No hedging. Bicofino does not explain what is obvious to those who understand football.',
  'voice.confident.label': 'Confident',
  'voice.confident.desc': 'Never tentative, never hedging. Statements, not suggestions.',
  'voice.editorial.label': 'Editorial',
  'voice.editorial.desc': 'Writing has rhythm. Word choice matters. Quality felt before it is read.',
  'voice.nocliches.label': 'No clichés',
  'voice.nocliches.desc': 'No "passionate about", "dedicated to", "committed to". Bicofino proves, not proclaims.',
  'voice.bilingual.label': 'Bilingual',
  'voice.bilingual.desc': 'Portuguese and English coexist naturally. Never literal translation — always cultural adaptation.',

  // Common
  'common.coming-soon': 'In development',
  'common.coming-soon-detail': 'This section is being built. Check back soon.',
  'common.wip': 'Work in Progress',

  // Section 03 — Components Gallery
  comp_eyebrow: 'Section 03',
  comp_heading: 'Components',
  comp_intro: 'All system components — every piece built on the same tokens.',

  comp_buttons_eyebrow: 'Buttons',
  comp_buttons_heading: 'Buttons',
  comp_buttons_desc: 'Four variants, three sizes, complete states.',
  comp_buttons_primary: 'Primary',
  comp_buttons_secondary: 'Secondary',
  comp_buttons_ghost: 'Ghost',
  comp_buttons_destructive: 'Destructive',
  comp_buttons_loading: 'Loading…',
  comp_buttons_disabled: 'Disabled',

  comp_cards_eyebrow: 'Cards',
  comp_cards_heading: 'Cards',
  comp_cards_desc: 'Base surface for grouping related content.',
  comp_cards_default: 'Default card',
  comp_cards_metric: 'Metric card',
  comp_cards_athlete: 'Athlete card',

  comp_charts_eyebrow: 'Charts',
  comp_charts_heading: 'Charts',
  comp_charts_desc: 'Data visualizations with dedicated color tokens.',
  comp_charts_line: 'Line',
  comp_charts_bar: 'Bar',
  comp_charts_donut: 'Donut',

  comp_forms_eyebrow: 'Forms',
  comp_forms_heading: 'Forms',
  comp_forms_desc: 'Inputs, selects and controls with validation states.',
  comp_forms_label_name: 'Name',
  comp_forms_placeholder_name: 'E.g.: John Smith',
  comp_forms_label_sport: 'Sport',
  comp_forms_label_active: 'Active athlete',
  comp_forms_label_notify: 'Receive notifications',

  comp_badges_eyebrow: 'Badges',
  comp_badges_heading: 'Badges',
  comp_badges_desc: 'Status, tags and labels — all color variants.',
  comp_badges_active: 'Active',
  comp_badges_inactive: 'Inactive',
  comp_badges_pending: 'Pending',
  comp_badges_new: 'New',
  comp_badges_featured: 'Featured',
  comp_badges_archived: 'Archived',

  comp_feedback_eyebrow: 'Feedback',
  comp_feedback_heading: 'Feedback',
  comp_feedback_desc: 'Alerts, toasts, empty states and skeletons.',
  comp_feedback_alert_success: 'Operation completed successfully.',
  comp_feedback_alert_warning: 'Warning: verify data before continuing.',
  comp_feedback_alert_error: 'Error processing the request.',
  comp_feedback_empty_title: 'No results',
  comp_feedback_empty_desc: 'Try adjusting filters or adding new data.',

  // Section 04 — Verticals
  vert_eyebrow: 'Section 04',
  vert_heading: 'Verticals',
  vert_intro: 'Bicofino Group operates on two editorial fronts. Each has its own visual expression, within the system.',

  vert_onfield_eyebrow: 'On-Field',
  vert_onfield_heading: 'On Field — Athlete Image System',
  vert_onfield_subhead: 'Image as presence. Data as proof.',
  vert_onfield_desc: 'The On Field system treats the athlete as the primary visual asset. Images are not placed inside generic cards — they create hierarchy, tension and presence. Data sustains the narrative with precision.',
  vert_onfield_tone: 'Football. Competition. Results. High-intensity communication — visual highlights, program colors, editorial urgency.',
  vert_onfield_serves: 'Who it serves',
  vert_onfield_serves_desc: 'Bicofino portfolio athletes — primarily young football talents with international career potential.',
  vert_onfield_delivers: 'What On Field delivers',
  vert_onfield_d1: 'Athlete representation and agency',
  vert_onfield_d2: 'Physical, tactical, mental and cognitive development',
  vert_onfield_d3: 'Performance and health monitoring',
  vert_onfield_d4: 'Club contract management',
  vert_onfield_d5: 'International market positioning',
  vert_onfield_d6: 'Media kit and athlete profile for scouts and clubs',
  vert_onfield_catalog: 'On Field Asset Structure',
  vert_onfield_cat_portraits: 'Athlete Portraits',
  vert_onfield_cat_campaigns: 'Campaign Images',
  vert_onfield_cat_brand: 'Personal Brand',
  vert_onfield_cat_badges: 'Bicofino Badges',
  vert_onfield_cat_clubs: 'Club Badges',
  vert_onfield_cat_sponsors: 'Sponsor Logos',
  vert_onfield_cat_passports: 'Passports / Nations',
  vert_onfield_cat_icons: 'Performance Icons',

  vert_offfield_eyebrow: 'Off-Field',
  vert_offfield_heading: 'Off Field — Beyond the Pitch',
  vert_offfield_subhead: 'Everything that exists off the pitch.',
  vert_offfield_desc: 'Off Field brings together all the services that make the athlete, brand, or company grow beyond sports performance. This is where Bicofino also serves brands and companies — with or without a direct connection to athletes.',
  vert_offfield_tone: 'Lifestyle. Culture. Premium living. Sophisticated editorial communication — quiet luxury, whitespace, typography, restraint.',
  vert_offfield_serves: 'Who it serves',
  vert_offfield_serves_desc: 'Portfolio athletes (off-pitch), premium brands and executives seeking high-level creative and strategic curation.',
  vert_offfield_delivers: 'What Off Field delivers',
  vert_offfield_d1: 'Branding and visual identity',
  vert_offfield_d2: 'Advertising and content production',
  vert_offfield_d3: 'Design, motion and art direction',
  vert_offfield_d4: 'PR and executive personal branding',
  vert_offfield_d5: 'Legal consulting and tax planning',
  vert_offfield_d6: 'Family office and financial planning',
  vert_offfield_d7: 'Connection between brands, athletes and personalities',
  vert_offfield_diff: 'The Off Field advantage',
  vert_offfield_diff_desc: 'Bicofino connects brands and companies to athletes, celebrities and personalities beyond the reach of most. This access was built with years of ethical relationships and consistent presence in the right markets.',

  // Section 05 — Assets
  assets_eyebrow: 'Section 05',
  assets_heading: 'Assets',
  assets_intro: 'Live components, sponsors and icon system.',

  assets_perf_eyebrow: 'Performance Intelligence',
  assets_perf_heading: 'Performance Intelligence',
  assets_perf_lead: 'Live visualization of the Bicofino OS system. Every number represents real efficiency — time recovered, output amplified, cost eliminated.',
  assets_perf_metrics_title: 'System Metrics',
  assets_perf_chart_title: 'Bicofino OS vs. Traditional',
  assets_perf_chart_lead: 'The compound advantage of Bicofino OS. The traditional line grows linearly — the Bicofino system grows exponentially.',
  assets_perf_c1_label: 'Time Saved / Week',
  assets_perf_c1_desc: 'Per consultant',
  assets_perf_c2_label: 'Output Multiplier',
  assets_perf_c2_desc: 'vs. traditional flow',
  assets_perf_c3_label: 'Cost Reduction',
  assets_perf_c3_desc: 'Operational overhead',
  assets_perf_c4_label: 'Efficiency Gain',
  assets_perf_c4_desc: 'Year over year',
  assets_perf_c5_label: 'Active Agents',
  assets_perf_c5_desc: 'In parallel',
  assets_perf_c6_label: 'Response Time',
  assets_perf_c6_desc: 'System average latency',

  assets_sponsors_eyebrow: 'Sponsors',
  assets_sponsors_heading: 'Sponsors',
  assets_sponsors_lead: 'Global brands and reference companies with which Bicofino maintains close relationships — built with access, trust and strategic context.',

  assets_icons_eyebrow: 'Icons',
  assets_icons_heading: 'Icons',
  assets_icons_lead: 'Lucide-based icon system. Consistent stroke, single weight, predictable scale. Click any icon to copy the React snippet.',
  assets_icons_copied: 'Copied!',
  assets_icons_copy_hint: 'Click to copy',

  // Section 06 — Operations
  ops_eyebrow: 'Section 06',
  ops_heading: 'Operations',
  ops_lead: 'Bicofino Group organizes its operations into two main verticals and one confidential project.',

  ops_arch_label: '// 06.1',
  ops_arch_title: 'Brand Architecture',

  ops_onfield_title: 'ON FIELD',
  ops_onfield_subtitle: 'Everything related to the athlete and their on-field performance',
  ops_onfield_desc: 'On Field brings together all services and specialists dedicated to the athlete as a performer. Doctors, physical performance specialists, nutritionists, sports psychologists, tactical coaches, data analysis technology — everything that enhances the athlete on the pitch.',
  ops_onfield_delivers: 'What On Field delivers:',
  ops_onfield_d1: 'Athlete representation and agency',
  ops_onfield_d2: 'Physical, tactical, mental and cognitive development',
  ops_onfield_d3: 'Performance and health monitoring',
  ops_onfield_d4: 'Club contract management',
  ops_onfield_d5: 'International market positioning',
  ops_onfield_d6: 'Media kit and athlete profile for scouts and clubs',
  ops_onfield_serves: 'Who it serves:',
  ops_onfield_serves_desc: 'Bicofino portfolio athletes — primarily young football talents with international career potential.',

  ops_offfield_title: 'OFF FIELD',
  ops_offfield_subtitle: 'Everything that exists off the pitch',
  ops_offfield_desc: 'Off Field brings together all the services that make the athlete, brand or company grow beyond sports performance. This is where Bicofino also serves brands and companies — with or without a direct connection to athletes.',
  ops_offfield_delivers: 'What Off Field delivers:',
  ops_offfield_d1: 'Branding and visual identity (athletes, brands, companies)',
  ops_offfield_d2: 'Advertising and content production',
  ops_offfield_d3: 'Design, motion and art direction',
  ops_offfield_d4: 'PR and executive personal branding',
  ops_offfield_d5: 'Legal consulting and tax planning',
  ops_offfield_d6: 'Family office and financial planning (Wealth)',
  ops_offfield_d7: 'Connection between brands, companies, athletes and personalities',
  ops_offfield_serves: 'Who it serves:',
  ops_offfield_serves_desc: 'Portfolio athletes (off-pitch), premium brands and executives seeking high-level creative and strategic curation.',
  ops_offfield_diff: 'The Off Field advantage:',
  ops_offfield_diff_desc: 'Bicofino connects brands and companies to athletes, celebrities and personalities beyond the reach of most. This access was built with years of ethical relationships and consistent presence in the right markets.',

  ops_club_title: 'CLUB',
  ops_club_subtitle: 'Raposa Territory — confidential',
  ops_club_desc: 'Club is Bicofino\'s most intimate and selective project. Its profile, criteria and members are kept in complete discretion.',
  ops_club_confidential: 'Details not publicly documented in this Brand System.',

  ops_visual_label: '// Visual architecture of verticals',
  ops_visual_desc: 'On Field and Off Field share the same visual DNA — Inter, diamond ✦, core palette, reading hierarchy. What differentiates them is the image universe:',
  ops_visual_onfield: 'always images of athletes on the pitch, in training, in competition',
  ops_visual_offfield: 'images of athletes in relation to brands, campaigns, companies and design — plus projects not involving athletes',

  ops_delivery_label: '// 06.2',
  ops_delivery_title: 'Delivery Standards',
  ops_delivery_desc: 'Every Bicofino output passes through the filter of the 6 Operation Principles before delivery:',
  ops_p1_title: 'Genuine obsession for detail',
  ops_p1_desc: 'Is there something here that can be more precise?',
  ops_p2_title: 'Beauty and intelligence in design',
  ops_p2_desc: 'Is this delivery both beautiful and strategic?',
  ops_p3_title: 'Deliver more than expected',
  ops_p3_desc: 'Will the client notice they received more than the brief?',
  ops_p4_title: 'Simple, never simplistic',
  ops_p4_desc: 'Is there anything that can be cut without losing substance?',
  ops_p5_title: 'Impact with elegance',
  ops_p5_desc: 'Is the message clear and delivered with the right tone?',
  ops_p6_title: 'Technology in service of creativity',
  ops_p6_desc: 'Were AI and data used as amplifiers?',

  ops_tools_label: '// Operation tools',
  ops_tools_col_role: 'FUNCTION',
  ops_tools_col_tool: 'TOOL',
  ops_tool_memory_role: 'Memory',
  ops_tool_memory_name: 'Google Drive + Supabase',
  ops_tool_org_role: 'Organization',
  ops_tool_org_name: 'Proprietary dashboard in development',
  ops_tool_orch_role: 'Orchestration',
  ops_tool_orch_name: 'Claude in terminal · AI agents in development',
  ops_tool_intel_role: 'Intelligence / Strategy / Copy',
  ops_tool_intel_name: 'Claude (primary) · ChatGPT · Gemini',
  ops_tool_design_role: 'Design / Interface',
  ops_tool_design_name: 'Photoshop · Illustrator · Claude Code (React, Tailwind, shadcn)',
  ops_tool_vi_role: 'Visual Identity',
  ops_tool_vi_name: 'Adobe Suite',
  ops_tool_video_role: 'Video Editing',
  ops_tool_video_name: 'Adobe Premiere',
  ops_tool_motion_role: 'Motion',
  ops_tool_motion_name: 'Claude Code (components) · After Effects',
  ops_tool_imggen_role: 'Image Generation',
  ops_tool_imggen_name: 'Magnific · ChatGPT',
  ops_tool_vidgen_role: 'Video Generation',
  ops_tool_vidgen_name: 'Magnific · Google VEO',

  ops_flow_label: '// Off Field delivery flow — Studio',
  ops_flow_s1: 'Brief or demand intake (Friday preferred)',
  ops_flow_s2: 'Production — 2 business days for recurring projects',
  ops_flow_s3: 'Internal review — 1 business day',
  ops_flow_s4: 'Delivery to client',
  ops_flow_s5: 'Revision round included in scope',
  ops_flow_s6: 'Approval and archiving',

  ops_commercial_label: '// Commercial policy',
  ops_policy1: 'No discount on value. Adjust via scope reduction, never quality.',
  ops_policy2: 'Limited schedule. Waitlist when necessary.',
  ops_policy3: 'Studio fees, media budget and production costs are separate, independent items.',
  ops_policy4: 'All proposals in dossier format — never price lists or packages.',

  ops_brand_line1: 'Brand System — Bicofino Group SA',
  ops_brand_line2: 'Developed and maintained by Studio Bicofino',
  ops_brand_line3: 'Woney Malian / Fabio Brancatelli',
  ops_brand_version: 'v1.0 · São Paulo, BR · May 2026',
  ops_brand_tagline: 'Unlike Any Other.',

  // Section 07 — Governance
  gov_eyebrow: 'Section 07',
  gov_heading: 'Governance',

  gov_ownership_eyebrow: 'Ownership',
  gov_ownership_heading: 'Version & Owners',
  gov_ownership_lead: 'Each layer of the system has a clear owner. Changes to Foundations require owner review. Components and Patterns can be proposed by any team member.',
  gov_col_layer: 'LAYER',
  gov_col_owner: 'OWNER',
  gov_col_scope: 'SCOPE',
  gov_foundations_scope: 'Tokens, typography, palette, grid',
  gov_brand_scope: 'Wordmark, voice, verticals',
  gov_components_scope: 'UI patterns, React/CSS code',
  gov_governance_scope: 'Version, changelogs, files',

  gov_resources_eyebrow: 'Resources',
  gov_resources_heading: 'Resources',
  gov_col_file: 'FILE',
  gov_col_purpose: 'PURPOSE',
  gov_r1_purpose: 'CSS custom properties — token source of truth',
  gov_r2_purpose: 'AI agent instructions — execution rules',
  gov_r3_purpose: 'Visual Identity Manual — editorial source of truth',
  gov_r4_purpose: 'Global project state and pending items',
  gov_r5_purpose: 'Navigation config — single source of truth for nav',
  gov_r6_purpose: 'Trilingual content — BR / EN / IT',
  gov_r7_purpose: 'Global providers — theme, language',
  gov_r8_purpose: 'Project progress tracker',
  skip_to_content: 'Skip to content',
} as const
