export const it = {
  // Site
  'site.title': 'Bicofino Design Studio',
  'site.description': 'Sistema visivo e di brand — riferimento completo di componenti e linee guida.',

  // UI controls
  'ui.theme.toggle': 'Cambia tema',
  'ui.lang.label': 'Lingua',
  'ui.menu.open': 'Apri menu',
  'ui.menu.close': 'Chiudi menu',

  // Language labels
  'lang.br': 'Português',
  'lang.en': 'English',
  'lang.it': 'Italiano',

  // Nav groups
  'nav.brand-system': 'Brand System',
  'nav.visual-system': 'Visual System',
  'nav.components': 'Componenti',
  'nav.verticais': 'Verticali',
  'nav.assets': 'Assets',
  'nav.operacoes': 'Operazioni',
  'nav.governanca': 'Governance',

  // Nav items
  'nav.fundamentos': 'Fondamenti',
  'nav.posicionamento': 'Posizionamento',
  'nav.nucleo': 'Nucleo del Brand',
  'nav.verbal': 'Universo Verbale',
  'nav.colors': 'Color Palette',
  'nav.typography': 'Tipografia',
  'nav.spacing-motion': 'Spacing & Motion',
  'nav.logo': 'Logo System',
  'nav.voice-tone': 'Voce & Tono',
  'nav.buttons': 'Bottoni',
  'nav.cards': 'Cards',
  'nav.charts': 'Grafici',
  'nav.forms': 'Form',
  'nav.badges': 'Badge',
  'nav.feedback': 'Feedback',
  'nav.on-field': 'On-Field',
  'nav.off-field': 'Off-Field',
  'nav.performance': 'Performance Intelligence',
  'nav.sponsors': 'Sponsor',
  'nav.icons': 'Icone',
  'nav.arquitetura': 'Architettura',
  'nav.delivery': 'Delivery',
  'nav.ownership': 'Ownership',
  'nav.resources': 'Risorse',

  // Overview
  'overview.eyebrow': '// BICOFINO DESIGN STUDIO',
  'overview.heading': 'Design System',
  'overview.intro': 'Il riferimento vivo di componenti, token e linee guida del brand Bicofino. Modulare, estensibile, costruito per evolversi.',

  // Brand System
  'fundamentos.eyebrow': '// 01 — FONDAMENTI',
  'fundamentos.heading': 'Fondamenti',
  'fundamentos.intro': 'I principi che strutturano tutte le decisioni visive e comunicative del brand.',

  'posicionamento.eyebrow': '// 01 — POSIZIONAMENTO',
  'posicionamento.heading': 'Posizionamento',
  'posicionamento.intro': "Come Bicofino si posiziona nel mercato e cosa la distingue nell'universo del calcio ad alte prestazioni.",

  'nucleo.eyebrow': '// 01 — NUCLEO DEL BRAND',
  'nucleo.heading': 'Nucleo del Brand',
  'nucleo.intro': "Scopo, missione e i quattro pilastri che definiscono l'identità Bicofino: Connect, Curate, Create, Consult.",

  'verbal.eyebrow': '// 01 — UNIVERSO VERBALE',
  'verbal.heading': 'Universo Verbale',
  'verbal.intro': 'La voce, il tono e il vocabolario del brand. Come parliamo, a chi parliamo e cosa non diciamo mai.',

  // Visual System
  'colors.eyebrow': '// 02 — COLOR PALETTE',
  'colors.heading': 'Color Palette',
  'colors.intro': 'Un sistema di colori chiuso. Ogni token ha una funzione — non esistono colori decorativi in Bicofino.',

  'typography.eyebrow': '// 02 — TIPOGRAFIA',
  'typography.heading': 'Tipografia',
  'typography.intro': 'Inter per display e corpo. JetBrains Mono per metadati, eyebrow e codice. Nient\'altro.',

  'spacing-motion.eyebrow': '// 02 — SPACING & MOTION',
  'spacing-motion.heading': 'Spacing & Motion',
  'spacing-motion.intro': 'Tre valori di spaziatura. Tre durate di animazione. Nessun valore intermedio.',

  'logo.eyebrow': '// 02 — LOGO SYSTEM',
  'logo.heading': 'Logo System',
  'logo.intro': 'Il logotipo, il diamante e le regole di utilizzo. Il brand come sistema, non come ornamento.',

  'voice-tone.eyebrow': '// 02 — VOCE & TONO',
  'voice-tone.heading': 'Voce & Tono',
  'voice-tone.intro': 'Diretta, tecnica, sicura. Bicofino parla a chi capisce di calcio.',

  // Components
  'buttons.eyebrow': '// 03 — BOTTONI',
  'buttons.heading': 'Bottoni',
  'buttons.intro': 'Tutti gli stati, le dimensioni e le varianti. Interazione chiara, feedback immediato.',

  'cards.eyebrow': '// 03 — CARDS',
  'cards.heading': 'Cards',
  'cards.intro': 'Contenitori di contenuto con gerarchia chiara. Stat card, athlete card, featured card.',

  'charts.eyebrow': '// 03 — GRAFICI',
  'charts.heading': 'Grafici',
  'charts.intro': 'Visualizzazioni animate dei dati di performance. SVG con ingresso spring, responsive.',

  'forms.eyebrow': '// 03 — FORM',
  'forms.heading': 'Form',
  'forms.intro': 'Input, select, checkbox. Stati di errore e validazione visiva integrati.',

  'badges.eyebrow': '// 03 — BADGE',
  'badges.heading': 'Badge',
  'badges.intro': 'Indicatori di stato, programma e categoria. Sistema badge On-Field.',

  'feedback.eyebrow': '// 03 — FEEDBACK',
  'feedback.heading': 'Feedback',
  'feedback.intro': "Toast, alert e indicatori di stato. Comunicazione chiara con l'utente.",

  // Verticals
  'on-field.eyebrow': '// 04 — ON-FIELD',
  'on-field.heading': 'On-Field',
  'on-field.intro': "L'universo visivo dell'atleta. Identità, performance e presenza in campo.",

  'off-field.eyebrow': '// 04 — OFF-FIELD',
  'off-field.heading': 'Off-Field',
  'off-field.intro': "L'estensione del brand fuori dal campo. Partner, club e operazioni commerciali.",

  // Assets
  'performance.eyebrow': '// 05 — PERFORMANCE INTELLIGENCE',
  'performance.heading': 'Performance Intelligence',
  'performance.intro': 'Dashboard e metriche che trasformano i dati in decisioni di carriera.',

  'sponsors.eyebrow': '// 05 — SPONSOR',
  'sponsors.heading': 'Sponsor',
  'sponsors.intro': "Partner e sponsor dell'ecosistema Bicofino.",

  'icons.eyebrow': '// 05 — ICONE',
  'icons.heading': 'Icone',
  'icons.intro': 'Lucide React, stroke 1.5, 20px. Nessuna icona piena.',

  // Operations
  'arquitetura.eyebrow': '// 06 — ARCHITETTURA',
  'arquitetura.heading': 'Architettura',
  'arquitetura.intro': "Come è strutturato l'ecosistema Bicofino: prodotti, team e flussi.",

  'delivery.eyebrow': '// 06 — DELIVERY',
  'delivery.heading': 'Delivery',
  'delivery.intro': 'Processi di consegna, versionamento e controllo qualità.',

  // Governance
  'ownership.eyebrow': '// 07 — OWNERSHIP',
  'ownership.heading': 'Ownership',
  'ownership.intro': 'Chi è responsabile di cosa nel design system Bicofino.',

  'resources.eyebrow': '// 07 — RISORSE',
  'resources.heading': 'Risorse',
  'resources.intro': 'Link, strumenti e documentazione di supporto.',

  // Visual System — Colors
  'color.black.role': 'Primario',
  'color.black.desc': 'Testo principale, sfondi scuri, icone',
  'color.steel.role': 'Secondario',
  'color.steel.desc': 'Testo di supporto, metadati, bordi medi',
  'color.aluminium.role': 'Terziario',
  'color.aluminium.desc': 'Sfondi di sezione, separatori leggeri',
  'color.platinum.role': 'Evidenziazione fredda',
  'color.platinum.desc': 'Highlight, gradienti di focus',
  'color.bg.role': 'Sfondo',
  'color.bg.desc': 'Sfondo pagina e superfici principali',
  'color.white.role': 'Bianco puro',
  'color.white.desc': 'Superfici card e overlay',
  'color.powerblack.role': 'Power Black',
  'color.powerblack.desc': 'Sezioni ad alto contrasto, cover scure',
  'color.crema.role': 'Crema',
  'color.caffe.role': 'Caffè',
  'color.champagne.role': 'Champagne',
  'color.cacao.role': 'Cacao',
  'colors.basics.title': 'Palette Base',
  'colors.specials.title': 'Colori Speciali',
  'colors.highlights.label': '// 02.2.3',
  'colors.highlights.title': 'Evidenziazioni — Atleti e Club',
  'colors.tokens.title': 'Riferimento Token',
  'token.black.role': 'Testo primario',
  'token.powerblack.role': 'Sfondo ad alto contrasto',
  'token.bg.role': 'Sfondo blu',
  'token.white.role': 'Superficie bianca',
  'token.steel.role': 'Testo secondario',
  'token.aluminium.role': 'Separatori e sfondi leggeri',
  'token.platinum.role': 'Evidenziazione fredda',
  'token.crema.role': 'Accento caldo chiaro',
  'token.caffe.role': 'Accento caldo scuro',
  'token.cacao.role': 'Marrone medio',
  'token.torino.role': 'Torino FC',
  'token.como.role': 'Como FC',
  'token.spfc.role': 'São Paulo FC',
  'table.col.token': 'Token',
  'table.col.value': 'Valore',
  'table.col.name': 'Nome',
  'table.col.role': 'Funzione',

  // Visual System — Typography
  'font.inter.subtitle': 'Display, titoli e testo corpo',
  'font.inter.family': 'Inter',
  'font.inter.weights': '400, 500, 600, 700',
  'font.inter.coverage': 'Latino esteso',
  'font.inter.usage': 'Tutti i testi display, heading e corpo',
  'font.inter.license': 'SIL Open Font License',
  'font.mono.subtitle': 'Metadati, eyebrow, codice e label',
  'font.mono.family': 'JetBrains Mono',
  'font.mono.weights': '400, 600',
  'font.mono.coverage': 'Latino',
  'font.mono.usage': 'Eyebrow, label tecnici, frammenti di codice',
  'font.mono.license': 'SIL Open Font License',
  'font.meta.family': 'Famiglia',
  'font.meta.weights': 'Pesi',
  'font.meta.coverage': 'Copertura',
  'font.meta.usage': 'Utilizzo',
  'font.meta.license': 'Licenza',
  'typescale.eyebrow.specimen': 'BICOFINO / 2026',
  'typescale.eyebrow.meta': '11px / 1.4 · 0.12em · 600 uppercase',

  // Visual System — Spacing & Motion
  'spacing.section.title': 'Token di Spaziatura',
  'spacing.col.token': 'Token',
  'spacing.col.px': 'px',
  'spacing.col.rem': 'rem',
  'spacing.col.usage': 'Utilizzo',
  'spacing.col.visual': 'Visuale',
  'motion.section.title': 'Durata del Movimento',
  'radius.section.title': 'Border Radius',
  'radius.label.sm': 'sm · 4px',
  'radius.label.md': 'md · 8px',
  'radius.label.lg': 'lg · 16px',
  'sp1.uso': 'Gap micro interno',
  'sp2.uso': 'Gap icona-label',
  'sp3.uso': 'Padding compatto',
  'sp4.uso': 'Padding pulsante / gap standard',
  'sp5.uso': 'Padding interno card',
  'sp6.uso': 'Padding sezione compatta',
  'sp7.uso': 'Padding sezione standard',
  'sp8.uso': 'Spaziatura tra blocchi',
  'sp9.uso': 'Margine pagina top/bottom',

  // Visual System — Logo System
  'brand.logo.light': '// sfondo chiaro',
  'brand.logo.dark': '// sfondo scuro',
  'brand.logo.crema': '// sfondo crema',
  'brand.logo.aluminium': '// sfondo alluminio',
  'brand.logo.sizes.label': '// dimensioni raccomandate',
  'brand.logo.sizes.display': 'display',
  'brand.logo.sizes.padrao': 'standard',
  'brand.logo.sizes.compacto': 'compatto',
  'brand.logo.sizes.minimo': 'minimo',
  'brand.logo.sizes.evitar': 'evitare',
  'brand.logo.minrec': '// dimensione minima raccomandata: 48px',
  'brand.logo.rules.label': '// regole d\'uso',
  'brand.logo.rule1': 'Non distorcere né alterare le proporzioni del logo.',
  'brand.logo.rule2': 'Non applicare ombre, gradienti o effetti visivi.',
  'brand.logo.rule3': 'Mantenere uno spazio libero minimo pari all\'altezza della lettera "B".',
  'brand.logo.rule4': 'Usare solo nelle versioni scura e chiara approvate.',
  'brand.diamond.label': '// diamante bicofino',
  'brand.diamond.lead': 'Il diamante è il simbolo di accesso ed eccellenza di Bicofino.',
  'brand.diamond.lead2': 'Usato da solo come icona di marca o in combinazione con il logo in contesti ad alto contrasto.',
  'brand.diamond.light': '// sfondo chiaro',
  'brand.diamond.dark': '// sfondo scuro',
  'brand.diamond.crema': '// sfondo crema',
  'brand.diamond.aluminium': '// sfondo alluminio',
  'brand.diamond.sizes.label': '// dimensioni raccomandate',
  'brand.diamond.minrec': '// dimensione minima raccomandata: 20px',

  // Visual System — Voice & Tone
  'voice.direct.label': 'Diretta',
  'voice.direct.desc': 'Frasi brevi. Senza giri di parole. Bicofino non spiega ciò che è ovvio per chi capisce di calcio.',
  'voice.confident.label': 'Sicura',
  'voice.confident.desc': 'Mai tentativa, mai esitante. Affermazioni, non suggerimenti.',
  'voice.editorial.label': 'Editoriale',
  'voice.editorial.desc': 'La scrittura ha ritmo. La scelta delle parole conta. Qualità che si sente prima di leggere.',
  'voice.nocliches.label': 'Senza cliché',
  'voice.nocliches.desc': 'Niente "appassionato di", "dedicato a", "impegnato per". Bicofino dimostra, non proclama.',
  'voice.bilingual.label': 'Bilingue',
  'voice.bilingual.desc': 'Portoghese e inglese convivono naturalmente. Mai traduzione letterale — sempre adattamento culturale.',

  // Common
  'common.coming-soon': 'In sviluppo',
  'common.coming-soon-detail': 'Questa sezione è in costruzione. Torna presto.',
  'common.wip': 'Work in Progress',

  // Section 03 — Components Gallery
  comp_eyebrow: 'Sezione 03',
  comp_heading: 'Componenti',
  comp_intro: 'Tutti i componenti del sistema — ogni pezzo costruito sugli stessi token.',

  comp_buttons_eyebrow: 'Buttons',
  comp_buttons_heading: 'Pulsanti',
  comp_buttons_desc: 'Quattro varianti, tre dimensioni, stati completi.',
  comp_buttons_primary: 'Primario',
  comp_buttons_secondary: 'Secondario',
  comp_buttons_ghost: 'Ghost',
  comp_buttons_destructive: 'Distruttivo',
  comp_buttons_loading: 'Caricamento…',
  comp_buttons_disabled: 'Disabilitato',

  comp_cards_eyebrow: 'Cards',
  comp_cards_heading: 'Card',
  comp_cards_desc: 'Superficie base per raggruppare contenuto correlato.',
  comp_cards_default: 'Card predefinita',
  comp_cards_metric: 'Card metrica',
  comp_cards_athlete: 'Card atleta',

  comp_charts_eyebrow: 'Charts',
  comp_charts_heading: 'Grafici',
  comp_charts_desc: 'Visualizzazioni dati con token colore dedicati.',
  comp_charts_line: 'Linea',
  comp_charts_bar: 'Barre',
  comp_charts_donut: 'Donut',

  comp_forms_eyebrow: 'Forms',
  comp_forms_heading: 'Moduli',
  comp_forms_desc: 'Input, select e controlli con stati di validazione.',
  comp_forms_label_name: 'Nome',
  comp_forms_placeholder_name: 'Es.: Mario Rossi',
  comp_forms_label_sport: 'Sport',
  comp_forms_label_active: 'Atleta attivo',
  comp_forms_label_notify: 'Ricevere notifiche',

  comp_badges_eyebrow: 'Badges',
  comp_badges_heading: 'Badge',
  comp_badges_desc: 'Stato, tag ed etichette — tutte le varianti di colore.',
  comp_badges_active: 'Attivo',
  comp_badges_inactive: 'Inattivo',
  comp_badges_pending: 'In attesa',
  comp_badges_new: 'Nuovo',
  comp_badges_featured: 'In evidenza',
  comp_badges_archived: 'Archiviato',

  comp_feedback_eyebrow: 'Feedback',
  comp_feedback_heading: 'Feedback',
  comp_feedback_desc: 'Avvisi, toast, stati vuoti e skeleton.',
  comp_feedback_alert_success: 'Operazione completata con successo.',
  comp_feedback_alert_warning: 'Attenzione: verificare i dati prima di continuare.',
  comp_feedback_alert_error: "Errore durante l'elaborazione della richiesta.",
  comp_feedback_empty_title: 'Nessun risultato',
  comp_feedback_empty_desc: 'Prova a regolare i filtri o ad aggiungere nuovi dati.',

  // Sezione 04 — Verticali
  vert_eyebrow: 'Sezione 04',
  vert_heading: 'Verticali',
  vert_intro: "Bicofino Group opera su due fronti editoriali. Ognuno ha la propria espressione visiva, all'interno del sistema.",

  vert_onfield_eyebrow: 'On-Field',
  vert_onfield_heading: 'On Field — Athlete Image System',
  vert_onfield_subhead: 'Immagine come presenza. Dati come prova.',
  vert_onfield_desc: "Il sistema On Field tratta l'atleta come il principale asset visivo. Le immagini non sono inserite in card generiche — creano gerarchia, tensione e presenza. I dati sostengono la narrativa con precisione.",
  vert_onfield_tone: 'Calcio. Competizione. Risultati. Comunicazione ad alta intensità — highlights visivi, colori di programma, urgenza editoriale.',
  vert_onfield_serves: 'Chi serve',
  vert_onfield_serves_desc: 'Atleti del portafoglio Bicofino — principalmente giovani talenti del calcio con potenziale di carriera internazionale.',
  vert_onfield_delivers: 'Cosa offre On Field',
  vert_onfield_d1: 'Rappresentanza e agenzia atleti',
  vert_onfield_d2: 'Sviluppo fisico, tattico, mentale e cognitivo',
  vert_onfield_d3: 'Monitoraggio performance e salute',
  vert_onfield_d4: 'Gestione contratti con i club',
  vert_onfield_d5: 'Posizionamento per mercati internazionali',
  vert_onfield_d6: 'Media kit e profilo atleta per scout e club',
  vert_onfield_catalog: 'Struttura Asset On Field',
  vert_onfield_cat_portraits: 'Ritratti Atleti',
  vert_onfield_cat_campaigns: 'Immagini Campagna',
  vert_onfield_cat_brand: 'Brand Personale',
  vert_onfield_cat_badges: 'Badge Bicofino',
  vert_onfield_cat_clubs: 'Stemmi Club',
  vert_onfield_cat_sponsors: 'Logo Sponsor',
  vert_onfield_cat_passports: 'Passaporti / Nazioni',
  vert_onfield_cat_icons: 'Icone Performance',

  vert_offfield_eyebrow: 'Off-Field',
  vert_offfield_heading: 'Off Field — Beyond the Pitch',
  vert_offfield_subhead: 'Tutto ciò che esiste fuori dal campo.',
  vert_offfield_desc: "Off Field riunisce tutti i servizi che fanno crescere l'atleta, il brand o l'azienda oltre la performance sportiva. È qui che Bicofino serve anche brand e aziende — con o senza connessione diretta con gli atleti.",
  vert_offfield_tone: 'Lifestyle. Cultura. Stile di vita premium. Comunicazione editoriale sofisticata — quiet luxury, spazio bianco, tipografia, restraint.',
  vert_offfield_serves: 'Chi serve',
  vert_offfield_serves_desc: "Atleti del portafoglio (extra-campo), brand premium ed executive che cercano curatela creativa e strategica di alto livello.",
  vert_offfield_delivers: 'Cosa offre Off Field',
  vert_offfield_d1: 'Branding e identità visiva',
  vert_offfield_d2: 'Advertising e produzione contenuti',
  vert_offfield_d3: 'Design, motion e direzione artistica',
  vert_offfield_d4: 'PR e personal branding executive',
  vert_offfield_d5: 'Consulenza legale e pianificazione fiscale',
  vert_offfield_d6: 'Family office e pianificazione finanziaria',
  vert_offfield_d7: 'Connessione tra brand, atleti e personalità',
  vert_offfield_diff: 'Il vantaggio Off Field',
  vert_offfield_diff_desc: 'Bicofino connette brand e aziende ad atleti, celebrità e personalità fuori dalla portata della maggior parte. Questo accesso è stato costruito con anni di relazioni etiche e presenza costante nei mercati giusti.',

  // Sezione 05 — Assets
  assets_eyebrow: 'Sezione 05',
  assets_heading: 'Asset',
  assets_intro: 'Componenti live, sponsor e sistema di icone.',

  assets_perf_eyebrow: 'Performance Intelligence',
  assets_perf_heading: 'Performance Intelligence',
  assets_perf_lead: 'Visualizzazione live del sistema Bicofino OS. Ogni numero rappresenta efficienza reale — tempo recuperato, output amplificato, costo eliminato.',
  assets_perf_metrics_title: 'Metriche del Sistema',
  assets_perf_chart_title: 'Bicofino OS vs. Tradizionale',
  assets_perf_chart_lead: 'Il vantaggio composto di Bicofino OS. La linea tradizionale cresce linearmente — il sistema Bicofino cresce esponenzialmente.',
  assets_perf_c1_label: 'Tempo Risparmiato / Settimana',
  assets_perf_c1_desc: 'Per consulente',
  assets_perf_c2_label: 'Moltiplicatore di Output',
  assets_perf_c2_desc: 'vs. flusso tradizionale',
  assets_perf_c3_label: 'Riduzione dei Costi',
  assets_perf_c3_desc: 'Overhead operativo',
  assets_perf_c4_label: 'Guadagno di Efficienza',
  assets_perf_c4_desc: 'Anno su anno',
  assets_perf_c5_label: 'Agenti Attivi',
  assets_perf_c5_desc: 'In parallelo',
  assets_perf_c6_label: 'Tempo di Risposta',
  assets_perf_c6_desc: 'Latenza media del sistema',

  assets_sponsors_eyebrow: 'Sponsor',
  assets_sponsors_heading: 'Sponsor',
  assets_sponsors_lead: 'Brand globali e aziende di riferimento con cui Bicofino mantiene relazioni strette — costruite con accesso, fiducia e contesto strategico.',

  assets_icons_eyebrow: 'Icone',
  assets_icons_heading: 'Icone',
  assets_icons_lead: 'Sistema di icone basato su Lucide. Tratto consistente, peso unico, scala prevedibile. Clicca su qualsiasi icona per copiare lo snippet React.',
  assets_icons_copied: 'Copiato!',
  assets_icons_copy_hint: 'Clicca per copiare',

  // Sezione 06 — Operazioni
  ops_eyebrow: 'Sezione 06',
  ops_heading: 'Operazioni',
  ops_lead: 'Bicofino Group organizza le sue operazioni in due grandi verticali e un progetto riservato.',

  ops_arch_label: '// 06.1',
  ops_arch_title: 'Architettura del Brand',

  ops_onfield_title: 'ON FIELD',
  ops_onfield_subtitle: "Tutto relativo all'atleta e alla sua performance in campo",
  ops_onfield_desc: "On Field riunisce tutti i servizi e gli specialisti dedicati all'atleta come performer. Medici, specialisti in performance fisica, nutrizionisti, psicologi sportivi, coach tattici, tecnologia di analisi dati — tutto ciò che potenzia l'atleta in campo.",
  ops_onfield_delivers: 'Cosa offre On Field:',
  ops_onfield_d1: 'Rappresentanza e agenzia atleti',
  ops_onfield_d2: 'Sviluppo fisico, tattico, mentale e cognitivo',
  ops_onfield_d3: 'Monitoraggio performance e salute',
  ops_onfield_d4: 'Gestione contratti con i club',
  ops_onfield_d5: 'Posizionamento per mercati internazionali',
  ops_onfield_d6: 'Media kit e profilo atleta per scout e club',
  ops_onfield_serves: 'Chi serve:',
  ops_onfield_serves_desc: 'Atleti del portafoglio Bicofino — principalmente giovani talenti del calcio con potenziale internazionale.',

  ops_offfield_title: 'OFF FIELD',
  ops_offfield_subtitle: 'Tutto ciò che esiste fuori dal campo',
  ops_offfield_desc: "Off Field riunisce tutti i servizi che fanno crescere l'atleta, il brand o l'azienda oltre la performance sportiva. È qui che Bicofino serve anche brand e aziende — con o senza connessione diretta con gli atleti.",
  ops_offfield_delivers: 'Cosa offre Off Field:',
  ops_offfield_d1: 'Branding e identità visiva (atleti, brand, aziende)',
  ops_offfield_d2: 'Advertising e produzione contenuti',
  ops_offfield_d3: 'Design, motion e direzione artistica',
  ops_offfield_d4: 'PR e personal branding executive',
  ops_offfield_d5: 'Consulenza legale e pianificazione fiscale',
  ops_offfield_d6: 'Family office e pianificazione finanziaria (Wealth)',
  ops_offfield_d7: 'Connessione tra brand, aziende, atleti e personalità',
  ops_offfield_serves: 'Chi serve:',
  ops_offfield_serves_desc: "Atleti del portafoglio (extra-campo), brand premium ed executive che cercano curatela creativa e strategica di alto livello.",
  ops_offfield_diff: 'Il vantaggio Off Field:',
  ops_offfield_diff_desc: 'Bicofino connette brand e aziende ad atleti, celebrità e personalità fuori dalla portata della maggior parte. Questo accesso è stato costruito con anni di relazioni etiche e presenza costante nei mercati giusti.',

  ops_club_title: 'CLUB',
  ops_club_subtitle: 'Territorio della Raposa — riservato',
  ops_club_desc: 'Il Club è il progetto più intimo e selettivo di Bicofino. Il suo profilo, i criteri e i membri sono mantenuti in totale discrezione.',
  ops_club_confidential: 'Dettagli non documentati pubblicamente in questo Brand System.',

  ops_visual_label: '// Architettura visiva delle verticali',
  ops_visual_desc: "On Field e Off Field condividono lo stesso DNA visivo — Inter, diamond ✦, palette core, gerarchia di lettura. Ciò che le differenzia è l'universo delle immagini:",
  ops_visual_onfield: 'sempre immagini degli atleti in campo, in allenamento, in competizione',
  ops_visual_offfield: 'immagini degli atleti in relazione a brand, campagne, aziende e design — oltre a progetti senza atleti',

  ops_delivery_label: '// 06.2',
  ops_delivery_title: 'Standard di Consegna',
  ops_delivery_desc: 'Ogni output Bicofino passa attraverso il filtro dei 6 Principi Operativi prima della consegna:',
  ops_p1_title: 'Ossessione genuina per i dettagli',
  ops_p1_desc: "C'è qualcosa qui che può essere più preciso?",
  ops_p2_title: 'Bellezza e intelligenza nel design',
  ops_p2_desc: 'Questa consegna è allo stesso tempo bella e strategica?',
  ops_p3_title: 'Consegnare più del previsto',
  ops_p3_desc: 'Il cliente noterà di aver ricevuto più del brief?',
  ops_p4_title: 'Semplice, mai semplicistico',
  ops_p4_desc: "C'è qualcosa che può essere tagliato senza perdere sostanza?",
  ops_p5_title: 'Incisività con eleganza',
  ops_p5_desc: 'Il messaggio è chiaro e consegnato con il tono giusto?',
  ops_p6_title: 'Tecnologia al servizio della creatività',
  ops_p6_desc: 'IA e dati sono stati usati come amplificatori?',

  ops_tools_label: '// Strumenti operativi',
  ops_tools_col_role: 'FUNZIONE',
  ops_tools_col_tool: 'STRUMENTO',
  ops_tool_memory_role: 'Memoria',
  ops_tool_memory_name: 'Google Drive + Supabase',
  ops_tool_org_role: 'Organizzazione',
  ops_tool_org_name: 'Dashboard proprietario in sviluppo',
  ops_tool_orch_role: 'Orchestrazione',
  ops_tool_orch_name: 'Claude nel terminale · Agenti IA in sviluppo',
  ops_tool_intel_role: 'Intelligenza / Strategia / Copy',
  ops_tool_intel_name: 'Claude (primario) · ChatGPT · Gemini',
  ops_tool_design_role: 'Design / Interfaccia',
  ops_tool_design_name: 'Photoshop · Illustrator · Claude Code (React, Tailwind, shadcn)',
  ops_tool_vi_role: 'Identità Visiva',
  ops_tool_vi_name: 'Pacchetto Adobe',
  ops_tool_video_role: 'Montaggio Video',
  ops_tool_video_name: 'Adobe Premiere',
  ops_tool_motion_role: 'Motion',
  ops_tool_motion_name: 'Claude Code (componenti) · After Effects',
  ops_tool_imggen_role: 'Generazione Immagini',
  ops_tool_imggen_name: 'Magnific · ChatGPT',
  ops_tool_vidgen_role: 'Generazione Video',
  ops_tool_vidgen_name: 'Magnific · Google VEO',

  ops_flow_label: '// Flusso di consegna Off Field — Studio',
  ops_flow_s1: 'Brief o ingresso domanda (venerdì preferenziale)',
  ops_flow_s2: 'Produzione — 2 giorni lavorativi per progetti ricorrenti',
  ops_flow_s3: 'Revisione interna — 1 giorno lavorativo',
  ops_flow_s4: 'Consegna al cliente',
  ops_flow_s5: 'Round di revisione incluso nello scope',
  ops_flow_s6: 'Approvazione e archiviazione',

  ops_commercial_label: '// Politica commerciale',
  ops_policy1: 'Nessuno sconto sul valore. Aggiustamento tramite riduzione di scope, mai di qualità.',
  ops_policy2: "Agenda limitata. Lista d'attesa quando necessario.",
  ops_policy3: 'Compensi Studio, budget media e costi di produzione sono voci separate e indipendenti.',
  ops_policy4: 'Tutte le proposte in formato dossier — mai listino prezzi o pacchetti.',

  ops_brand_line1: 'Brand System — Bicofino Group SA',
  ops_brand_line2: 'Sviluppato e mantenuto da Studio Bicofino',
  ops_brand_line3: 'Woney Malian / Fabio Brancatelli',
  ops_brand_version: 'v1.0 · São Paulo, BR · Maggio 2026',
  ops_brand_tagline: 'Unlike Any Other.',

  // Sezione 07 — Governance
  gov_eyebrow: 'Sezione 07',
  gov_heading: 'Governance',

  gov_ownership_eyebrow: 'Ownership',
  gov_ownership_heading: 'Versione & Owner',
  gov_ownership_lead: 'Ogni layer del sistema ha un responsabile chiaro. Le modifiche ai Foundations richiedono la revisione degli owner. Components e Patterns possono essere proposti da qualsiasi membro del team.',
  gov_col_layer: 'LAYER',
  gov_col_owner: 'OWNER',
  gov_col_scope: 'SCOPE',
  gov_foundations_scope: 'Token, tipografia, palette, grid',
  gov_brand_scope: 'Wordmark, voce, verticali',
  gov_components_scope: 'UI pattern, codice React/CSS',
  gov_governance_scope: 'Versione, changelog, file',

  gov_resources_eyebrow: 'Risorse',
  gov_resources_heading: 'Risorse',
  gov_col_file: 'FILE',
  gov_col_purpose: 'SCOPO',
  gov_r1_purpose: 'CSS custom properties — fonte di verità per i token',
  gov_r2_purpose: 'Istruzioni per agenti IA — regole di esecuzione',
  gov_r3_purpose: 'Manuale di Identità Visiva — fonte di verità editoriale',
  gov_r4_purpose: 'Stato globale del progetto e attività in sospeso',
  gov_r5_purpose: 'Configurazione navigazione — unica fonte di verità del nav',
  gov_r6_purpose: 'Contenuto trilingue — BR / EN / IT',
  gov_r7_purpose: 'Provider globali — tema, lingua',
  gov_r8_purpose: 'Tracker di avanzamento del progetto',
  skip_to_content: 'Vai al contenuto',
} as const
